### ISSUE TITLE
Add the term "instance (of a VM)"?

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#102]
[originally reported Mar 5, 2014 in Trello.]

**Comment by dariavladykina** [comment]
In doc-sle alone, we have 'Apache instance', 'program instance', 'image instance', 'GPU instance', 'public cloud instance', 'application instance', 'database instance', 'shell instance', 'virtual machine instance', to name a few.
I don't think this term needs a separate entry in the DB.

**Comment by jfaltenbacher** [comment]
Yep, I think so too and here as well, it's a commonly used term.
