### ISSUE TITLE
standardize one/multiple of: app(lication), software, program(me)..?

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#104]
+ **proposal**:
  + allow *program* for an individual executable/a suite of executables
  + allow *software* as a generic term to cover the entire category

+ issues:
  + *program* is not very sexy
  + *application* sounds too much like a GUI application, does not fit small utilities (tail, cat) or necessities (GRUB) well
  + *software* does not have a plural and sounds like a category name
  + a font e.g. is *software*, but neither *application* nor *program* (although the term *font program* is not unheard of).
  + what to do with *script*, *command*, *tool*?

From GitHub https://github.com/SUSE/doc-styleguide/issues/3

Here are some definitions from https://www.wordnik.com:

* command:
  * A directive to a computer program acting as an interpreter of some kind, in order to perform a specific task.
  * A signal that initiates an operation defined by an instruction.
* tool:
  *  An application program, often one that creates, manipulates, modifies, or analyzes other programs.
  * A mechanical device intended to make a task easier
  * A piece of software used to develop software or hardware, or to perform low-level operations.
* program
  * A software application, or a collection of software applications, designed to perform a specific task.
  * a sequence of instructions that a computer can interpret and execute
* application
  * A computer program with a user interface.
  * A computer program or the set of software that the end user perceives as a single entity as a tool for a well-defined purpose. (Also called: application program; application software.)

[originally reported Feb 25, 2014 in Trello.]

**Comment by sknorr** [comment]
toms, Apr 30, 2014 at 4:24 PM
> Well, fonts a special. ;) Although a font contains some kind of a program (byte code interpreter for hinting) I would never say a "font software" or "font program" unless I refer to this special piece. In this (special?) case, I would write "font file". It's neutral, in most cases it's correct, and avoids these kind of problems.

toms, Apr 30, 2014 at 4:27 PM
> What about the term suite? Should we define that too?
> Usually, we say "suite" when we refer to a set of programs which creates a common layout with shared functionality, like the "LibreOffice suite".

sknorr May 5, 2014 at 4:59 PM
> I would not go into suite right now, you could use program suite without a problem. So... this is really rather an orthogonal discussion.
> Also, to be perfectly nitpicky here, LibreOffice actually is just one application (hence, when LibreOffice crashes, it crashes as a whole, not by module).

**Comment by dariavladykina** [comment]
Proposal of definitions to include in the style guide:

- software
Written programs or procedures or rules and associated documentation pertaining to the operation of a computer system and that are stored in read/write memory (www.wordnik.com).

- suite
A set of computer programs designed to work together and usually sold as a single unit (www.merriam-webster.com).

**Comment by jfaltenbacher** [comment]
here I am unsure if we really should discuss this. 
Well, we can discuss, agree, and write it down but I believe hardly nobody will check whether he/she is using the term `software`, `application`, or `software` correctly - they will just keep using whatever they are used to.

**Comment by dariavladykina** [comment]
Thank you @jfaltenbacher for a sober thought here. I'm closing this now :+1:
