### ISSUE TITLE
add "hotfix"?

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#105]
[originally reported Apr 24, 2014 in Trello.]

**Comment by dariavladykina** [comment]
1 mention in doc-sle
0 mentions in doc-ses
0 mentions in doc-sleha

Microsoft, Apple, RedHat and Google do not list either of these terms in their word lists.

If we decide to add 'hotfix', should we also add 'patch'?

**Comment by jfaltenbacher** [comment]
I would not add generic and commonly known terms. This will only blow up the terminology list.
Maybe here as well, Stefan needed an agreed spelling for the stylechecker...?

**Comment by dariavladykina** [comment]
Closing this issue now for low relevance.
