### ISSUE TITLE
standardize refer v/ see v/ see also

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#106]
* accept: see, reject refer
* accept: see also, reject also refer

[originally reported Apr 1, 2014 in Trello.]

**Comment by sknorr** [comment]
It probably makes sense to standardize more than just the whether to use see or refer but standardize the whole sentence that goes along with it -- that should be a really quick way to generate 90+% matches in translation.

I tend to like these versions best:

```
For more information, see [xref].
For more information about [topic], see [xref].
For more information, see also [xref].
```

* "for more information" first, so the user knows what they're clicking on before they click
* "about" and not "on", to avoid ambiguities
