### ISSUE TITLE
What terminology do customers expect?

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#110]
Ideas...

+ ke:
  + expect usual Unix/Linux slang
  + using e.g. *sync* or *symlink* as nouns (but not as verbs!) seems good
+ fs:
    The majority of our documentation is written for administrators, the rest for experienced Linux users (the only exception may be the GNOME User guide for SLED). I would assume that our customers are used to a technical language containing typical Unix/Linux terms and probably even expect Linux manuals to be written in such a language. Therefore we should not try to avoid such terms. What's more, customers with a Unix or a non-SUSE Linux background should find a familiar terminology when reading our manuals.

[originally reported Mar 17, 2014 in Trello.]

**Comment by dariavladykina** [comment]
It seems to me that we do not avoid such terms in our docs, what do you think? Shall we discuss this more?

**Comment by dariavladykina** [comment]
Leaving this to the writers' common sense and closing.
