### ISSUE TITLE
Make style guide more useful as a quick reference.

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#111]
- [x] More lists, fewer long paragraphs in Language
- [x] More lists, fewer long paragraphs in Managing Documents
- [x] More lists, fewer long paragraphs in Structure
- [x] Consider creating an index

[originally reported Mar 4, 2014 in Trello.]

**Comment by dariavladykina** [comment]
The DSG is clear and concise as it is, closing this now.
