### ISSUE TITLE
No concrete recommendation for headline wording made

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#112]
+ **proposal**
  + description of an action: gerund, (article [etc.],) noun [plural where appropriate\*], e.g. *Installing the Network Drivers*
  + description of  an object: (article,) noun, e.g. *The Network Drivers*

+ Novell's osstyle.pdf: gerund
+ style checker could check for verbs in gerund & startswith != (how to)

\* which is where?

[originally reported Mar 19, 2014 in Trello.]

**Comment by dariavladykina** [comment]
This proposal has been implemented in the DSG, so closing the issue.
