### ISSUE TITLE
Explain similarities between variablelists and formalparas within a list

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#113]
Formalparas can be quite nice when one needs a more compact list.

Give recommendations where to use which.

[originally reported Mar 19, 2014 in Trello.]

**Comment by dariavladykina** [comment]
I did some research but am still not sure why compare `formalpara` with `variablelist`?

**Comment by jfaltenbacher** [comment]
I propose to close this as won't fix, purpose is also unclear to me

**Comment by cwickert** [comment]
This is about https://tdg.docbook.org/tdg/5.2/formalpara.html

A `<formalpara>` is a paragraph with a title. It's formatted as a displayed block and the title is is often rendered as a run-in head.

This is useful if you don't want to start a new section which would then show up in the TOC.

**Comment by dariavladykina** [comment]
Here's how it looks:
![image](https://github.com/SUSE/doc-styleguide/assets/98878014/87252e13-2e44-4dbd-9d66-ade609ab3f3c)

![image](https://github.com/SUSE/doc-styleguide/assets/98878014/aa9d35a3-975c-41a5-b812-bdc18e351fd7)

**Comment by dariavladykina** [comment]
How about just adding some info to the "Structure elements" table? 

`formalpara`  A paragraph with the title rendered as a run-in head

**Comment by jfaltenbacher** [comment]
I was thinking about this tonight... How about recommending adding a colon after the title. Like this
 <formalpara>
```
 <title>foo:<title>
 <para>
 This is about foo.
 <para>
```
This may make the title character more clear in the rendered output

**Comment by dariavladykina** [comment]
In this case, we also should recommend capitalizing the next word after this colon for visibility reasons.
Let's see what the committee decides.

**Comment by dariavladykina** [comment]
This was sorted, too, closing.
