### ISSUE TITLE
compress/decompress

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#115]
*Adding one or more files to a compressed archive, such as a ZIP or TGZ archive.*

**Contenders**: (to) zip, (to) compress, (to) add to archive, (to) tar

**Caveat**: Term should cover a newly created archive; archive formats that are not compressed (like plain TAR).

---

*Retrieving one or more files from a compressed archive, such as a ZIP or TGZ archive.*

**Contenders**: (to) unzip, (to) decompress, (to) uncompress, (to) untar, (to) extract, (to) remove

**Caveat**: Term should cover extracting all files from an archive; archive formats that are not compressed (like plain TAR).

[originally reported May 26, 2014 in Trello.]

**Comment by dariavladykina** [comment]
Google uses 'extract'
Microsoft uses zip (compress) and unzip (extract)
Apple uses compress and unzip (expand)

**Comment by PadraigDillon1** [comment]
All seem like valid options. Is the objective to standardize on just one?
