### ISSUE TITLE
add term "Filesystem Hierarchy Standard"

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#117]
(uses Filesystem as one word, unlike generic usages.)

[originally reported jun 2, 2014 in Trello.]

**Comment by dariavladykina** [comment]
I cannot tell whether we need this term - please share your knowledge!

**Comment by jfaltenbacher** [comment]
`filesystem` alone is often used, but this is a common term which I would not define it as terminology.
Maybe Stefan needed a preferred spelling for the spell-checker - I would adhere to the writing rules from Jacobs guide here

**Comment by dariavladykina** [comment]
I will make sure to add this to the spell-checker and will close this issue.
