### ISSUE TITLE
Access permissions v/ access rights..?

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#118]
access permissions? access rights? any other terms?
[originally reported Aug 12, 2014 in Trello.]

**Comment by dariavladykina** [comment]
"Access permission(s)" prevails over "access right(s)" by a count of 4, and [Google Trends](https://trends.google.com/trends/explore?date=today%205-y&q=access%20permission,access%20right&hl=ru) like it more.

**Comment by PadraigDillon1** [comment]
Both are fine for me also.
