### ISSUE TITLE
new term: userspace, user-space, user space (... land)

### ISSUE THREAD

**Issue by tomschr** [SUSE/doc-styleguide#12]
For example, as in:

```
[...] providing the core virtualization infrastructure and processor-specific drivers, and a
userspace program qemu-system-ARCH that provides [...]
```

Define the term and correct spelling:

* userspace?
* user space?
* user-space?

Same for "userland". See also the Wikipedia article: https://en.wikipedia.org/wiki/User_space

For consistency reasons, it would probably be good to use a space like in "user name".

Maybe it's good to define also the kernel space (with, without space or dash).

**Comment by sknorr** [comment]
Good one, and one I'd actually thought about before. Another synonym is `user[ -]?land`. Opposite is `kernel[ -]?(land|space)`.
So, "user space" and "kernel space" sound best to me.

**Comment by cwickert** [comment]
Two separate words is correct, so "user space" and "kernel space" it is. Lets however avoid *land.
