### ISSUE TITLE
Terminology to use for Web UIs

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#121]
e.g. 'screen' vs. 'view' (because most times, terms derived from windowed environments, like 'dialog box' would not be appropriate)

[originally reported Feb 3, 2016 in Trello.]

**Comment by cwickert** [comment]
I suggest "view", because for me a screen is the whole (e. g. the whole content of the browser window) whereas a view can also be a smaller part of the UI. Also, you can switch to a different view, but not to a different screen.

**Comment by dariavladykina** [comment]
I agree since we also use <screen> as an inline element.
I like this recent definition of `view` from [IBM](https://www.ibm.com/docs/en/baw/20.x?topic=concepts-views). We cannot borrow it directly but we can modify it and add to the terms. `screen` would be added to the 'Rejected' column.

**Comment by jfaltenbacher** [comment]
I would not reject `screen`. It just stands for another concept. I understand `screen` as the entire window (like in: See the message displayed on the screen).
Whereas `View` is just showing a smaller part of the screen and sometimes it is used in the meaning of "filtering" (like: Define a views for each user group (some see more content, some see less content)

**Comment by dariavladykina** [comment]
OK, suggest definition of `screen` then:

([Merriam](https://www.merriam-webster.com/dictionary/screen)) The surface on which the image appears in an electronic display (as in a computer terminal); _also_ the information displayed on a computer screen at one time.

**Comment by dariavladykina** [comment]
Merged, can be closed
