### ISSUE TITLE
multiversion vs. multi-version?

### ISSUE THREAD

**Issue by taroth21** [SUSE/doc-styleguide#122]

**Comment by Loquacity** [comment]
So, generally speaking, compound words move from being two words, to being hyphenated, to being one word over time. How long that period is depends on how much the word is used, how easily understandable it is in its different formats ("co-operate" for example, is harder to recognise and needed to be more widely used before it dropped its hyphen in common use), and also which corpus of English you are dealing with. Words move slower through this process in en-GB than they do in en-US. I find that the best way to find where a word is currently at in the process is to use ngrams. 

![image](https://user-images.githubusercontent.com/3914967/81626943-5ac68980-9440-11ea-88c9-697aaee5edae.png)

And, for comparison, the en-GB corpus:
![image](https://user-images.githubusercontent.com/3914967/81626986-73cf3a80-9440-11ea-9c57-13f5fc9f96c9.png)

**Comment by dariavladykina** [comment]
The Marketing team advises to go with the hyphenated version :+1: 
So, we can add the adjective `multi-version`, as this is not going to be a noun or a verb.

**Comment by dariavladykina** [comment]
Merged, can be closed.
