### ISSUE TITLE
rewriteable vs. re-writeable?

### ISSUE THREAD

**Issue by taroth21** [SUSE/doc-styleguide#123]

**Comment by Loquacity** [comment]
![image](https://user-images.githubusercontent.com/3914967/81627183-f821bd80-9440-11ea-93ce-5f493ebe8e38.png)

**Comment by asettle** [comment]
Don't know how much this accounts for, but I've never written "re-writeable" only ever "rewriteable" :shrug:

**Comment by sknorr** [comment]
* On the hyphenation front: we don't need to specifically define this: there should _not_ be a hyphen: https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-prefix

* "writable" v/ "writ*e*able" would be worth discussing, however, MW defines [writable](https://www.merriam-webster.com/dictionary/writable), no "e".

* Lastly, the word sounds a bit ridiculous and I am wondering if it should be avoided in general. But I guess it has meaning, and it's not easily paraphrased.

-> I'd add it to the spellcheck dictionary, nothing else.

**Comment by dariavladykina** [comment]
Since this has been added to the spell-checker and confirmed by MW, this issue can be safely closed.
