### ISSUE TITLE
why no use semicolon?

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#125]
As part of an effort to include reasonings for certain style decision, we should include a reasoning why we do not like semicolons. Abridged convo from Rocketchat:

> asettle: This is a genuine question: How do I explain to a technical author that the use of the semi-colon is not better than separating the two sentences appropriately?

> toms: I found only an article on Grammarly how to use semicolon correctly: https://www.grammarly.com/blog/semicolon/ Probably not really helpful.

> stfnknorr: longer sentences are generally worse -- and semicolons muddy the distinction. they are also hard to use correctly and harder to understand because they're less common.

> lproven: TL;DR – semicolons are extremely hard to use correctly, and unless you feel that you could be a professional editor in English as written by native speakers, the simplest rule is: never use semicolons. Ever.
>   I have read multiple summaries trying to explain how to do it correctly, what rules to follow, etc. It seems to be almost impossible to describe. So: don't. Just don't. At all, ever.

> stfnknorr: also of note: we have lots of non-native readers. if we can help them understand us better without having to be less precise in our wording, that is good.

> dpopov: Turn the tables on them and ask them to one good reason for using semicolon.

**Comment by Loquacity** [comment]
From my poster collection: https://theoatmeal.com/comics/semicolon

Jokes aside, we should be erring on the side of simplified technical English, which uses all standard English punctuation marks except the semicolon.

**Comment by dariavladykina** [comment]
I do not think we need to further explain this in the style guide :-) I will close this question.
