### ISSUE TITLE
Better distinguish between initial SLE major releases and later SPs

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#126]
This one was brought up by @fsundermeyer : We are currently using e.g. "SLES 15 GA" (GA = General Availability) for the initial version of a SLES major version. Later service packs are then, "SLES 15 SP1", "SLES 15 SP2", ...

The usage of "GA" has a couple of issues:

* GA is a complete SUSE-ism that is not understood in the wider populace, probably including a significant percentage of our customers/partners
* GA is also (or originally?) used for the initial release image. E.g. in IBS, we have `... :GA` and `... :Update` repos for all SLE product versions including minor versions. Technically, designations like "SLES 12 SP1 GA" are not wrong either, e.g. to distinguish between a system that was just installed versus a system that is for example fully updated.

I am not aware of any sort of real guidance from PM what this version should be called. I am also not aware whether it is understood that being able to differentiate between "SLES 15" = "a series of one initial major release and subsequent service packs" versus "SLES 15" = "the initial major release" is an issue. (However, it is an issue because both features and support time frames differ significantly between each minor release of the same series.)

Frank suggests using "SP0"/"Service Pack 0" but that seems rather weird as well, even though I am almost sure I have seen it in some release announcement mail too.

**Task here would be to find out how product management/marketing see this issue and whether we can improve/standardize our usage in documentation.**

**Comment by Loquacity** [comment]
I would argue that GA is pretty widely used in software development, but that's still not a good argument for using it.

**Comment by sknorr** [comment]
You're right -- "complete SUSE-ism" was an exaggeration. Acronymfinder does list GA for General Availability, though not among the top 5, https://www.acronymfinder.com/GA.html

**Comment by lproven** [comment]
How about just %major-version-number% dot zero, e.g. "15.0"?

**Comment by sknorr** [comment]
We can't just invent a `.0`. In fact, _inventing_ anything here is _bad_. We really need to talk to PM/marketing.

**Comment by janajaeger** [comment]
Close this one. This is a non-issue. We just have to use whatever marketing comes up with.
