### ISSUE TITLE
Update style guide to (somewhat) match branding people's ideas about language

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#127]
The branding people have created a language guide, we should try to make sure we are not in open conflict with it wherever possible. cf. https://links.imagerelay.com/cdn/3404/ql/16eb71bffe01474b966406dd17650cd1/SUSE_ToV_content_guide.pdf

**Comment by cwickert** [comment]
I agree we can safely close this ticket. It was just a placeholder to not forget about the 'Tone of Voice' guide. We have reviewed it now and the conclusion was that documentation must have a different ToV. Just one example: the guide recommends a 'touch of humor', but even the slightest touch is too much for documentation.
