### ISSUE TITLE
(update) channel v/ repository

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#13]
We should use "repository" everywhere except in the SUSE Manager documentation where "channel" is both important and differently defined.

**Comment by dariavladykina** [comment]
I've found some docs where "channel" is still used in the meaning of "repository."
I suggest adding this item to Terminology and TermWeb.

**Comment by cwickert** [comment]
Definitely "repository". Unfortunately new terms like "online channels" have occurred in the meantime. :-/

**Comment by cwickert** [comment]
We agreed on the following:

* Repository is correct in most cases. Already in TermWeb.
* Channel is a group of repositories. Needs to be added to TermWeb.

**Comment by dariavladykina** [comment]
Added to TermWeb, closing the issue.

**Comment by dariavladykina** [comment]
FTR: Jana H. has confirmed that for `transactional-updates`, it is safe to use "repository" instead of "channel". So only SUMA keeps actively using "channel" for a group of repos.
