### ISSUE TITLE
Define xrefstyle attribute usage guidelines

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#130]
This was a remark in the style guide (in id=sec-cross-reference) but it makes more sense as an issue:
>  <remark>toms, Dec 2013: How do we use the attribute xrefstyle?</remark>

**Comment by dariavladykina** [comment]
Does this attribute still exist or is it needed?

**Comment by cwickert** [comment]
Yes it is. It defines the display of xrefs, for example if only the title is shown ("Foo") or also the the numbering with book/chapter/section numbering ("Chapter 5 Section 5.4 Foo").

 Currently I'm seeing the following styles in `doc-sle`

- `select:label`
- `select:label nopage` (for callouts)
- `select:nopage` (for callouts)
- `select:label title nopage`
- `select:label quotedtitle nopage`
- `select:title`
- `SectTitleOnPage`
- `ChapTitleOnPage`
- `HeadingOnPage`
- `StepOnPage`
- `FigureXRef` (only used twice in `xml/storage_lvm.xml`)
- `StepXRef` (only used once in `xml/apparmor_managing.xml`)
- `TableXRef` (only used 5 times in `xml/storage_filesystems.xml`)
- `template:Combustion` (only used once in `xml/art_installation-sle-micro.xml`, which is no longer published. I doubt this ever worked or was necessary)
- `template:Ignition` (just like `template:Combustion`)

@tomschr, can you shed some light on this? The 'select' ones are easy, but what does 'nopage' do and what are the other styles for?

**Comment by tomschr** [comment]
> can you shed some light on this? The 'select' ones are easy, but what does 'nopage' do and what are the other styles for?

Sure!

* Everything that starts with `select:...` is described in the [DocBook XSL: The Complete Guide: Using select](http://www.sagehill.net/docbookxsl/CustomXrefs.html#UsingSelect).
  The content here are keywords written as _names_. Each keyword (like `title`) acts as a placeholder and is replaced by the real content. You can't add arbitrary text inside the `xrefstyle` attribute.
* Everything that starts with `template:...` is described in [DocBook XSL: The Complete Guide: Using template](http://www.sagehill.net/docbookxsl/CustomXrefs.html#UsingTemplate).
  The content here are text mixed with keywords written in the form of `%n`. Each placeholder is also replaced by the real content. However, you can mix fixed text with placeholders (in contrast to `select`).
* Anything else (like `SectTitleOnPage`) is a leftover from Novell. :wink: I think you can savely remove them, they aren't interpreted by the stylesheets.

I would suggest to remove everything from the `xrefstyle` attribute that doesn't fall into one of the `select` or `template` category.

**Comment by dariavladykina** [comment]
Hi @tomschr, thanks for your suggestion. Please remove everything except for `select` and `template`. Thanks!!!

**Comment by tomschr** [comment]
I'm not sure if I have enough time for this ATM. Either find another person who would do that or you need to wait a bit longer. :slightly_smiling_face:

**Comment by cwickert** [comment]
I removed the obsolete xrefstyles in doc-sle with https://github.com/SUSE/doc-sle/commit/d978c5df7fb619a70e79af0a5c881b6a4f11099b

@dariavladykina, how about we add the two links @tomschr presented to the [relevant section of the style guide](https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-cross-reference)? Something along the lines of
> To control how references are displayed, you can use the xrefstyle attribute. For more info, refer to…

After that, we should be good and can close this issue.
