### ISSUE TITLE
Update introductory sections to reflect structural changes, AsciiDoc guidance

### ISSUE THREAD

**Issue by taroth21** [SUSE/doc-styleguide#132]
https://documentation.suse.com/style/current/single-html/docu_styleguide/#art-styleguide:

From the intro: "The GeekoDoc/DocBook markup reference at the end of this guide will help you choose the right XML element for your purpose. "

The reference is not clear. If it is referring to one of the following sections, they are not (no longer?) at the end of guide:  
https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-format-xml
https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-structure

Also, the intro does not mention AsciiDoc at all.

**Comment by sknorr** [comment]
It's referring to the Structure section (though mostly because the formatting section did not exist when the intro was written).

**Comment by dariavladykina** [comment]
This has been fixed in #227, closing the issue now.
