### ISSUE TITLE
Mention support for language attribute in screens

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#133]
Our HTML builds now support automatic syntax highlighting when using `<screen language="...">...</screen>`. That should be mentioned/explained, with all supported values also mentioned.

**Comment by cwickert** [comment]
This should be added to sec-screen. Do we have a list of supported languaged?

**Comment by janajaeger** [comment]
List of supported languages pulled from https://github.com/openSUSE/suse-xsl/blob/main/suse2022-ns/xhtml/param.xsl:
`apache|bash|c++|css|diff|html|xml|http|ini|json|java|javascript|makefile|nginx|php|perl|python|ruby|sql|crmsh|dockerfile|lisp|yaml`
Reassigning to Daria.

**Comment by dariavladykina** [comment]
Closing this as the respective PR has been merged.
