### ISSUE TITLE
Style Guide is very DocBook-centric

### ISSUE THREAD

**Issue by taroth21** [SUSE/doc-styleguide#134]
https://documentation.suse.com/style/current/single-html/docu_styleguide/#art-styleguide

All of the examples are taken from DocBook. With Chapter 5 (Structure and Markup) we have a comprehensive chapter on using DocBook elements, while Chapter 8 (Working with AsciiDoc) basically only gives some pointers. Chapter 6 (Managing Documents) is only about Docbook, too. When revising the guide, we should keep an eye  on more parity between DocBook and AsciiDoc. 

Alternatively: 

- Only keep the highlevel stuff (like Audience - Names of Example items - Outline of a Manual - Language - Terminology and General Vocabulary) in the style guide (and make Chapter 7 "Formatting XML" more generic and less DocBook-centric)? 
- Move the details about DocBook/AsciiDoc to a different place?

**Comment by sknorr** [comment]
My idea from ca. yesterday was that we could keep the structure essentially as is but profile for AsciiDoc v/ DocBook, meaning we'd have two guides, each showing examples only for a specific format. Not sure if that would work properly yet, would need a bit of analyzing content in the current Structure section.

**Comment by Loquacity** [comment]
SUMA team has the very beginnings of a markup guide for adoc, here: https://github.com/uyuni-project/uyuni-docs/wiki/markup-syntax Would probably be good to have this at a higher level, since more people are using adoc now.
