### ISSUE TITLE
Names of Example Items section should reference doc-kit-shipped entities

### ISSUE THREAD

**Issue by taroth21** [SUSE/doc-styleguide#136]
2  Names of Example Items:
https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-name

"At least some of the following names should be provided through entities. "

For DocBook, maybe add link to the following example entity files in doc-kit?

https://github.com/openSUSE/doc-kit/blob/main/entities/generic-entities.ent
https://github.com/openSUSE/doc-kit/blob/main/entities/network-entities.ent

**Comment by dariavladykina** [comment]
I think it makes sense to finish this statement "At least some of the following names should be provided through entities." It looks cut off.

**Comment by jfaltenbacher** [comment]
Isn't it more like 
"Some of the following names are covered through entities. Refer to (add ink to network and generic entity files here)"
