### ISSUE TITLE
[doc] 4.2  Capitalization and Title Style

### ISSUE THREAD

**Issue by taroth21** [SUSE/doc-styleguide#138]
4.2  Capitalization and Title Style:
https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-capitalization

Please don't kill me but let's discuss if we want to keep suggesting title style for all our headlines... 
IIRC, the UI/UX team goes for sentence style in their EOS guidelines because they argued that many developers do not even know that different capitalization styles exist nor would they expect them to learn the title style capitalization rules. The same is true for our external contributors. Whenever I review a PR that's one of the major issues to fix and it is quite time-consuming to do so. I'd rather invest the time in making the titles match the section content (for example, phrasing procedure titles with the -ing form to reflect that the reader needs to take action) than fixing capitalization.

**Comment by sknorr** [comment]
> don't kill me

Not going to. :) Iirc, Liam also criticized it as too American. Personally, I still think it looks better but it even when done correctly, it has practical issues. E.g. when attempting to use entities that normally include a lower-case word in titles.

**Comment by Loquacity** [comment]
I would dearly love to drop title case. Personally, I think it's becoming old fashioned. Not many modern style guides recommend it these days.

**Comment by sknorr** [comment]
I think we fixed that :woot:

cf. 44105db2636a39aa00b27689852f6a34b49afdc9
