### ISSUE TITLE
Give guidance on punctuation to use at the end of list items

### ISSUE THREAD

**Issue by taroth21** [SUSE/doc-styleguide#139]
4.10  Lists:
https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-lists

Which punctuation to use at the end of list items is always a topic. Can we provide some more guidance here? (for example, add the advice _not_ to use commas and a full stop with the last item - this is painful if the items ever need to be resorted or some are removed). 

I would also suggest to use similar grammatical structures for all list items and give an example.

**Comment by sknorr** [comment]
#137 is related and should probably be updated to fix this issue as well

**Comment by dariavladykina** [comment]
Doc Style Guide: 
If each item in a list consists of a single sentence only, do not use a period at the end of items.
If at least one list item consists of two full sentences, end all items in that list with a period.

Compare to SUSE Style Guide:
Use periods, not semicolons, at the end of each section, whether it is a full sentence or a phrase.

**Comment by janajaeger** [comment]
I like the AP based suggestion very much. Strongly reeks of common sense ;)

**Comment by dariavladykina** [comment]
Closing the issue as this has been merged.
