### ISSUE TITLE
For DocBook, recommend 100-char lines & 2-space indent?

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#141]
We currently recommend 80-char lines and a 1-space indent for our DocBook documents.

However,

* 1-space indents are extremely non-standard and hard to set up in some editors. They are also hard to visually discern.
* The 80-char limits stems from the default size of terminal windows in the 80s (and from the fact that some co-workers used 10" laptops 15 years ago). However, modern laptops generally have screens wide enough to display 200 or more characters per line. This setting is also somewhat connected to the 1-char indent -- double the indent also means we will get double the indent depth.

For AsciiDoc, none of this is relevant, since the format barely has any indents and the recommended style is sentence-per-line.

**Comment by cwickert** [comment]
I agree to all of the above. The recommendation from the title – 2 chars indention and 100 char line length – seems reasonable to me.

However we would need to change that not only in the style guide but also in `daps-xmlformat` once we agree on something.

**Comment by dariavladykina** [comment]
I agree to the 2 char indention and 100 char line length (this will be added to section 'Formatting XML').
Shall we ask @tomschr to add it to `daps-xmlformat`?

**Comment by tomschr** [comment]
To be precise: the `daps-xmlformat` script is just a wrapper around `xmlformat`. The place where we need to add it is our [configuration file](https://github.com/openSUSE/daps/blob/main/etc/docbook-xmlformat-1.9.conf).

As far as I can see, we need to add `subindent` with the following change in `daps/etc/docbook-xmlformat-1.9.conf`:

```diff
diff --git i/etc/docbook-xmlformat-1.9.conf w/etc/docbook-xmlformat-1.9.conf
index 35477ecd..16004783 100644
--- i/etc/docbook-xmlformat-1.9.conf
+++ w/etc/docbook-xmlformat-1.9.conf
@@ -3,6 +3,7 @@
 
 *DEFAULT
   wrap-type     none
+  subindent     2
```

I've tested it and it looks good.

**Comment by janajaeger** [comment]
@tomschr have these changes been applied, yet? If so, close this issue. If not, can you apply them and close it afterwards.

**Comment by cwickert** [comment]
@dariavladykina, it seems this never made it into the Style Guide. It still reads: 

> Indentation:  Indent using a single space character per indentation level.

Right now, we have a mismatch between `daps-xmlformat` and the guide.

**Comment by dariavladykina** [comment]
Closing this as it has finally been accommodated.
