### ISSUE TITLE
Standardize file names of images

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#143]
Similar to #15, we should come up with a file name standard for images. To be done after #15...

**Comment by jfaltenbacher** [comment]
naming conventions for images are mentioned in chapter [7.4.2 File names](https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-file-markup) but could be more prominent

**Comment by dariavladykina** [comment]
Add link to README in doc-modular (both in Figures and File names): https://github.com/SUSE/doc-modular/blob/main/templates/README.md
