### ISSUE TITLE
Can we simplify the trademark guidance?

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#145]
https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-trademark asks writers to follow the rule to only use the trademarked version of a product name on its first occurrence within a chapter but not on later occurrences. This is problematic both because it prevents effective use of entities but also because it seems like unnecessary mental overhead. In practice, this results in our documentation being non-compliant with our own guidelines in most cases.

We should check with Legal if we can just remove all the trademark mentions. Our legalnotice also contains some language about trademarks, maybe we can expand that wording to say that we don't assume trademarks are ours etc. (Current language: "For SUSE trademarks, see https://www.suse.com/company/legal/. All other third party trademarks are the property of their respective owners. Trademark symbols (®, ™ etc.) denote trademarks of &suse; and its affiliates. Asterisks (*) denote third-party trademarks.")

Alternatively, we should probably make sure to use the appropriate trademark on all mentions of the trademarked word. That would still be a bit of a pita for writers but at least it would be consistent and easy to resolve with XML entities/Asciidoc attributes.

(via @KucharczykL )

**Comment by janajaeger** [comment]
Given that it might take longer to clarify than adding the default option (with TM) to the entity definition, I'm with Stafan and Lukas.

**Comment by jfaltenbacher** [comment]
I don't think we can leave out the trademarks entirely. I found this guidance https://www.inta.org/wp-content/uploads/public-files/resources/consumer/2020_TMUseMediaInternetPublishing.pdf

**Comment by dariavladykina** [comment]
I'm strongly in favor of using trademarks on their first occurrence only. 
There are entities like `susereg` and `slereg` (for SUSE® Linux Enterprise) and `&trademark;` for ™ in doc-kit.
We have guidance on how to use them and we provide info where to look them up. This seems enough to me.

**Comment by PadraigDillon1** [comment]
Does the issue still exist that in a modular doc world the first instance in one piece of content may not be the first location in another.  Is there a way around that?

**Comment by janajaeger** [comment]
> Does the issue still exist that in a modular doc world the first instance in one piece of content may not be the first location in another. Is there a way around that?

No, there is no way of knowing which instance comes first. The only thing we can do is add the TM and friends for the first occurrence per file. A file could be the first in once article and come fourth in another. Although, if we managed to somehow squeeze all of the TMed terms into the info section of the assembly, we could use them there and keep the topics free of trademarks. But as we don't know whether this is possible for each and every term and article, we need to play safe and go by topic :(

**Comment by cwickert** [comment]
Long story short: Let's stick to trademarking the first occurrence. Should cover most cases, even in modular docs.

**Comment by PadraigDillon1** [comment]
Response from Chioma Benjamin:
We don't need to use the (superscript) 'TM' symbol - the trade mark is effective without the TM symbol.

**Comment by PadraigDillon1** [comment]
[Query on TM symbol.txt](https://github.com/SUSE/doc-styleguide/files/14210076/Query.on.TM.symbol.txt)
Email exchange with Chioma Benjamin attached confirming no legal requirements for TM symbols.
