### ISSUE TITLE
Create hierarchy for heading levels in docs

### ISSUE THREAD

**Issue by asettle** [SUSE/doc-styleguide#146]
Suggestion from Lana in #144 

> Headings should be as simple as possible, and should always be written in simple present tense (the action is happening right now). Use declarative noun phrases as much as possible.
> 
> For sections that contain a procedure, use the bare infinitive (base) form of the verb followed by the subject. For example: Install SUSE Manager, or Configure the Client.
> 
> Procedure titles should always begin with a gerund. For example, Installing SUSE Manager, or Configuring the Client.
Use present continuous tense for procedure titles (the action is happening now, and will continue into the future).
> 
> H1 Potatoes
> (Concepts)
> 
> H2 Peel Potatoes
> (Description of the procedure, and how it fits into the process)
> 
> H3 Procedure: Peeling Potatoes
> (Steps)

**Comment by dariavladykina** [comment]
Closing this as resolved with #144
