### ISSUE TITLE
Inclusive Naming initiative 

### ISSUE THREAD

**Issue by sknorr** [SUSE/doc-styleguide#148]
* We should add the terms from https://inclusivenaming.org/language/word-list/ to Terminology (currently just three, so extremely doable)
* We should probably add a link to the initiative's home page to our style guide somewhere in the Tone/Voice section.

@asettle volunteered to be a point of contact for the initiative within our team. (Not sure what that entails though.) (Iiuc, please correct if this is not accurate.)

**Comment by sknorr** [comment]
PR #150 is related...

**Comment by cwickert** [comment]
In the light of more inclusive naming, I just filed #158.
