### ISSUE TITLE
Setup & Configuration

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#152]
via @dmpop 

> We need to have a clear distinction between setup and configuration. I usually use setup when I describe an arrangement of several hardware or software components. I use configuration when I describe settings of a specific application or hardware component. So a backup solution consisting of, say, a client application and a back end, is a backup setup, while a tool like, say, snapper doesn't have a setup, it has configuration. I mention that, because Snapper Setup in https://susedoc.github.io/doc-sle/main/single-html/SLES-administration/#cha-snapper doesn't sound right to me. Opinions and thoughts?

**Comment by dariavladykina** [comment]
Right now we have this (ambiguous to me) note for 'configuration': noun; unless when referring to file extension. 
We already have a definition of 'setup' in TermWeb, and I suggest adding one for 'configuration' in TermWeb (and remove it from DSG later).

I've found these:
[Techtarget](https://www.techtarget.com/whatis/definition/configuration)
[Techopedia](https://www.techopedia.com/definition/4250/configuration#:~:text=Configuration%20is%20the%20manner%20in,software%20components%20as%20software%20configuration.)
[Computerhope](https://www.computerhope.com/jargon/c/configur.htm)

I would use something like this: 
The arrangement of the functional units of a computer system according to their nature, number and chief characteristics.

**Comment by PadraigDillon1** [comment]
That definition looks good to me for Configuration. We should add it to Termweb and get it translated in the first translation cycle

**Comment by dariavladykina** [comment]
"Setup" and "configuration" are now both in TermWeb, closing.
