### ISSUE TITLE
Usage & utilization

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#153]
We should probably try to improve the definition of usage and utilization. Our current style guide completely forbids "utilization" in favor of "usage" but there are enough spots where the latter cannot replace the former (hardware utilization and hardware usage are absolutely not the same thing).

**Comment by Loquacity** [comment]
What's wrong with "use" in all cases?

**Comment by sknorr** [comment]
"Hardware use" and "hardware utilization" are very different things. (Sorry, belated response.)

**Comment by dariavladykina** [comment]
in the doc-sle repo, we only have 2 instances of 'utilization' referring to CPU
in doc-sleha, there are a lot of instances, 90% of which are 'utilization attribute(s)'
doc-ses mainly features 'memory utilization'

We can add 'utilization' in such phrases and provide examples.

Reference:
[Merriam-Webster](https://www.merriam-webster.com/dictionary/utilize): Choose the Right Synonym for utilize
[USE](https://www.merriam-webster.com/dictionary/use), [EMPLOY](https://www.merriam-webster.com/dictionary/employ), [UTILIZE](https://www.merriam-webster.com/dictionary/utilize) mean to put into service especially to attain an end. [USE](https://www.merriam-webster.com/dictionary/use) implies availing oneself of something as a means or instrument to an end.  willing to use any means to achieve her ends  [EMPLOY](https://www.merriam-webster.com/dictionary/employ) suggests the use of a person or thing that is available but idle, inactive, or disengaged.  looking for better ways to employ their skills  [UTILIZE](https://www.merriam-webster.com/dictionary/utilize) may suggest the discovery of a new, profitable, or practical use for something.  an old wooden bucket utilized as a planter

https://writing-point.fsv.cuni.cz/grammar-and-usage/use-utilize-employ/

https://www.manageengine.com/network-monitoring/memory-monitoring.html

**Comment by jfaltenbacher** [comment]
sounds like a decent solution for me

**Comment by dariavladykina** [comment]
In this case, we should provide `usage` with a definition and add `utilization` separately.

`usage`  the way in which something is used, or the amount of it that is used
`utilization` an act or instance of making practical or profitable use of something, _especially_ in _CPU utilization, memory utilization_.

**Comment by dariavladykina** [comment]
Merged, can be closed.
