### ISSUE TITLE
"For more information" is a bit odd as a section title

### ISSUE THREAD

**Issue by sknorr** [SUSE/doc-styleguide#154]
via @dmpop: We use "For more information" as the title for sections that include links to other sources. This title is a little _awkward_ because it sounds like the beginning of a sentence but it is not. We should therefore switch to "More information".

This section name is referenced in the Outline section but we should also check whether it makes sense to expand the General vocabulary section

(For the practical part of the exercise, we have at least the following variants in the SLE docs which should be made consistent: "For more information", "Additional information", "More information", "Further information")

**Comment by cwickert** [comment]
Suggestion: "Further Reading"

If it turns out we also link videos or media that are not read, we should to for "Further Information".

**Comment by cwickert** [comment]
As agreed in the 2012-02-25 Stylewich meeting, it's "More information". @sknorr will file a PR for this.

**Comment by sknorr** [comment]
Closed with 5211f483.
