### ISSUE TITLE
Example user names

### ISSUE THREAD

**Issue by cwickert** [SUSE/doc-styleguide#158]
We currently use free-software mascots, such as Tux (kernel), Wilber (GIMP) or Geeko (SUSE) as example names.

This is what we have in doc-sle's entity-decl.ent right now:
```
<!ENTITY exampleuser_plain    "tux">
<!ENTITY exampleuser    "<systemitem xmlns='http://docbook.org/ns/docbook' class='username'>&exampleuser_plain;</systemitem>">

<!ENTITY exampleuserII_plain    "wilber">
<!ENTITY exampleuserII  "<systemitem xmlns='http://docbook.org/ns/docbook' class='username'>&exampleuserII_plain;</systemitem>">

<!ENTITY exampleuserIII_plain    "geeko">
<!ENTITY exampleuserIII "<systemitem xmlns='http://docbook.org/ns/docbook' class='username'>&exampleuserIII_plain;</systemitem>">

<!ENTITY exampleuserfull    "Tux Linux">
<!-- Do not use Gimp as the last name, what with negative connotations etc.
     Instead use "fox," even though Wilber is not a fox: http://gimp-savvy.com/ABOUT/index.html -->
<!ENTITY exampleuserIIfull  "Wilber Fox">
<!ENTITY exampleuserIIIfull "Suzanne Geeko">
```

PROBLEMS
1. Inconsistent: For the last name, we distinguish between plain name and name with markup. Full name on the other hand is only plain.
2. Inconsistent: If full name is only plain, it should be called `exampleuserfull_plain`, `exampleuserIIfull_plain` and `exampleuserIIIfull`.
3. Inconsistent: While example users `exampleuser` and `exampleuserII` are first names, `exampleuserIII` is the last name.
4. Not inclusive: Only one first name is female. As it's the last one and because of the aforementioned inconsistency, **only a single out of all 213 occurrences** in doc-sle is female.
5. Not diverse: All names are English only.
6. Incomplete: No entities for first names. Would be useful for stuff like LDAP (security guide).
7. Trademarked: Linux is a trademark. Also, we sell solutions these days, not just Linux.
8. Geeko is outdated: Even if it's the name of (open)SUSE's very own mascot, marketing decided to ditch this name in 2010. Nobody understands the "geek" reference these days, in fact we don't want our products to be for geeks only. Error-prone because it can be confused with "gecko" and contributes to the gecko vs. chameleon confusion.

SUGGESTION

While the inconsistencies are trivial, we should pay attention to inclusiveness and diversity (refer to #148).

I see two possible paths there:
1. Unisex names like https://www.whattoexpect.com/baby-names/unisex-baby-names/ 
2. Well-known placeholder names such as "Jane Doe" or "John Doe". Use the female by default. Can be localized for more diversity, see https://en.wikipedia.org/wiki/List_of_terms_related_to_an_average_person

STATS

number of occurrences in doc-sle:
exampleuser: 30 occurrences
exampleuser_plain: 106
exampleuserII: 29
exampleuserII_plain: 12
exampleuserIII: 11
exampleuserIII_plain: 23
exampleuserfull: 0
exampleuserIIfull: 1
exampleuserIIfull: 1

**Comment by cwickert** [comment]
Regarding "Geeko", here is a mail from 2016:

```
Date: Tue, 4 Oct 2016 17:01:01 +0000
From: "Scott Corfield"
To: "DL-SU-All"
Subject: Is He a Chameleon or Gecko?

All,

There has been some recent discussions and questions within the company about 
our SUSE mascot, which I would like to clear up today. Some have asked if our 
mascot is a chameleon or a gecko.

Our mascot is a chameleon.

The confusion probably started more than 10 years ago when we gave our mascot a 
name (Geeko) during an internal competition. Some must have assumed that since 
his name was Geeko, he must be a gecko-but he's not.

Six years ago we made the decision to retire the Geeko name in hopes it would 
prevent further confusion. So moving forward, please do not refer to our 
chameleon mascot as Geeko or as a gecko.

Contact me if you have any questions, thx!!
```

Even though Scott is probably not 100% correct about the date (6 years before 2016 means 2010, but "Geeko" was [still used in 2011 for the "Geeko Gazette" newsletter)](https://www.suse.com/company/newsletter/suse-geeko-gazette-oct2011_1.html), we really should not use the name any longer.

**Comment by sknorr** [comment]
>1. Unisex names like https://www.whattoexpect.com/baby-names/unisex-baby-names/
>2. Well-known placeholder names such as "Jane Doe" or "John Doe". Use the female by default. Can be localized for more diversity, see https://en.wikipedia.org/wiki/List_of_terms_related_to_an_average_person

I like option (1) much more than preferring clearly female names which imo is just as bad as preferring male names. One the other hand, a lot of the supposedly gender-neutral names sound either clearly male or clearly female to me (= non-native speaker) anyway, so it comes out to about the same.

**Comment by cwickert** [comment]
Just as clarification: My idea was to make exampleuser female (Jane Doe) and exampleuserII male (John Doe). I doubt there are placeholder families (at least not in many languages), so for exampleuserIII we need something different anyway. We could then again take a female name or an unisex one – assuming there are well-known ones.

For exampleuser III we would likely have to go for something else – I doubt there are placholder families in many languages

**Comment by sknorr** [comment]
> My idea was to make exampleuser female (Jane Doe) and exampleuserII male (John Doe).

So, for one, Jane Doe and John Doe look very similar. I am not sure I would use them together, it would be better if the names were more different from each other, also in light of the fact that a lot of our readers are not native speakers and may be more easily confused there than natives. (Their German counterparts Max Mustermann and Erika Mustermann are much better at being distinctive.)

For two, example user \#1 will be used _much_ more often than \#2. This means, in a sense, \#1 always gets preferential treatment.

**Comment by lproven** [comment]
I would favour a list of names which are both gender-neutral _and_ international.

There are not many, but we do not need many, so coming up with a very short list should not be too hard.

I did some research, consulted multiple websites, and weeding out some names I consider confusing/inappropriate (for example, many people now use placenames as given names), here are my results.

### Gender neutral given names in English (sorted alphabetically)

Alex
Cameron
Drew
Jan
Jordan
Kim
Lee
Max
Pat
Robin
Sam

### Some of the most common surnames

* UK
  * Bloggs -- used as a generic or placeholder name in the UK, e.g. "Joe Bloggs"
  * Doe -- the comparable placeholder name in the US, e.g. "John Doe" or "Jane Doe"

* UK/US:
  * Smith
  * Jones
  * Williams
  * Brown
  * Johnson
  * Lee

* Hispanophone world:
  * Garcia
  * Rodriguez
  * Martinez
  * Hernandez
  * Lopez

* Korea (over 50% of people)
  * Kim
  * Lee
  * Park
  * Choi/Chong/Jung

* Chinese diaspora:
  * Wang -- but this has an unfortunate meaning in US English

* South Asia
  * Singh -- the mandated surname for all Sikh men and widely used in other cultures
  * Also Devi, Patel

### Conclusion

Jan, Kim, Lee and Park are all familiar and commonly-used names to several totally different cultural/language/national groups.

**Comment by cwickert** [comment]
I decided it's not worth opening yet another can of worms!
