### ISSUE TITLE
systemd init script v/ unit file

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#16]
Investigate if we should add a terminology entry asking writers not to use "systemd init script" (correction would be "systemd unit file"). While we are at it, we could also avoid using the more colloquial "systemd unit" (i.e. without the file).

**Comment by sknorr** [comment]
It's a "unit file" and it should be noted that unit files can do more than SysV init scripts ever could (e.g. there are timer unit files). The term "init script" comes from SysV and is now mostly obsolete.

**Comment by jfaltenbacher** [comment]
fine to me, would be just good to know, when the unit files were introduced, so that we know, which versions of our documentation are effected

**Comment by janajaeger** [comment]
> fine to me, would be just good to know, when the unit files were introduced, so that we know, which versions of our documentation are effected

Basically they should have been introduced with systemd which was 10+ years ago.

**Comment by cwickert** [comment]
@jfaltenbacher SLE 12 and 15 use systemd, only SLE 11 still ues SysVinit

**Comment by cwickert** [comment]
'systemd init script' is definitely wrong (even though systemd has support for these scripts). 

However I don't agree to `unit` vs. `unit file`. Both are distinct:

- A unit can be a service, socket, device, mount point, timer, etc., see https://www.freedesktop.org/software/systemd/man/systemd.unit.html
- The unit file is the configuration file of the unit and its suffix defines the unit type (`.service`, `.socket`, etc.)

Unless you talk about the file itself, you refer to the unit, not it's unit file: You enable/disable a unit, not the unit file; you start or stop the unit, and so one. Only when talking to the _physical_ file and not the unit as a _concept_, we should use the term `unit file'.

**Comment by cwickert** [comment]
I'll create a PR for the terminlogy table.

**Comment by cwickert** [comment]
PR merged, closing!
