### ISSUE TITLE
Do not use the term 'best effort'

### ISSUE THREAD

**Issue by cwickert** [SUSE/doc-styleguide#160]
This came up in https://bugzilla.suse.com/show_bug.cgi?id=1182706 

> Please do not use the term 'best effort' in our documentation.
> Instead please use 'economically reasonable effort'.

Applies to support statements (support levels, supported hypervisors, and VM guests).

**Comment by sknorr** [comment]
I don't know about this one. Almost seems like an overexplanation.

**Comment by dmpop** [comment]
Yup, just don't use it, instead replacing it with something clunky like _economically reasonable effort_. For example:

> The following guest operating systems are supported on a best-effort basis (L2, fixes if reasonable)

This can be simply reworded:

_The following guest operating systems receive L2 support and possible fixes_

**Comment by Loquacity** [comment]
I think the important thing here is that we always write in present tense. Avoiding declarations of things that might or might not happen in the future is just good practice (not to mention that "economically reasonable effort" is :vomiting_face: ).

**Comment by sknorr** [comment]
Lana:
>I think the important thing here is that we always write in present tense. Avoiding declarations of things that might or might not happen in the future is just good practice

Generally true, but this one is mostly about the support levels we define in the release notes (I think).
I tend to agree with Dima's general idea on wording here (''receive [...] possible fixes" sounds like bad English to my ears though).


----

heads up @KucharczykL -- You may be interested in this issue.

**Comment by Loquacity** [comment]
> I tend to agree with Dima's general idea on wording here (''receive [...] possible fixes" sounds like bad English to my ears though).

"is eligible to receive"?

**Comment by cwickert** [comment]
The bug this originated from is currently under review by legal. We should wait for their decision before we move on here.

**Comment by dariavladykina** [comment]
There are still 2 instances in `doc-sle`, none found in other repos. 
We could just rephrase them in the current documentation set so that they are saved for future writing.

**Comment by dariavladykina** [comment]
This is worked on in https://bugzilla.suse.com/show_bug.cgi?id=1207998, so closing here.
