### ISSUE TITLE
Tag version specific images

### ISSUE THREAD

**Issue by cwickert** [SUSE/doc-styleguide#167]
Updating images such as screenshots is a recurring – and cumbersome – task. In order to make it easier and prevent us from missing images, we could tag images whether they need to be updated or not.

Basically there are three different types of images:

* version-agnostic: _usually_ does not need to be updated. Of course it can change over time, but it's not _expected_ to change frequently / with every release. Probably the most common case, thus no special tag.
* version-dependent: _usually_ updated with every release, e.g. screenshots of the installer. If a screen does not change, it does not need to be updated, but we should make sure to check. Suggested tag: `check`.
* version-specific: _must_ be updated with every release because it contains a version string or something version-dependent. Suggested tag: `update`.

We could reduce it further to two cases (update and don't update).

Example
```
<figure xml:id="fig-install-zseries-dasd">
 <title>DASD disk management</title>
 <mediaobject role="check">
  <textobject role="description">
   <phrase>DASD Disk Management</phrase>
  </textobject>
  <imageobject role="fo">
   <imagedata width="100%" fileref="install_zseries_dasd.png"/>
  </imageobject>
  <imageobject role="html">
   <imagedata width="100%" fileref="install_zseries_dasd.png"/>
  </imageobject>
 </mediaobject>
</figure>
```
I use the `role` attribute here because it adds a "[user-specified classification for an element](https://tdg.docbook.org/tdg/5.1/ref-elements.html#common.attributes)", but there may be something better.

**Comment by sknorr** [comment]
`@role` probably is the best option for DocBook. Not sure if there's anything we could do in AsciiDoc, though. However, there's a good chance that doing it with a user-defined does not scale -- there will be lots of people who will either miss that we have a convention for this now or who will be unsure of the correct value to use (the style checker could help there but hey).

Related: For the SLE release notes (AsciiDoc), I just used regular comments to mark specific notes as `// !STICKY` (i.e. need to be kept for the next release). But the release notes are a vastly smaller problem, as only Lukáš, Frank, and me need to know the convention.

**Comment by janajaeger** [comment]
I'm with Stefan on this one. Not sure the criteria really help. I think adding categories here add to complexity, but doesn't help as you would have to recheck anyway.

**Comment by jfaltenbacher** [comment]
I totally understand Christoph's need. If there is an attribute or alike for this it would be possible to run a check and have all the screens that either need update or check listed. That is way faster then having to scroll through all images.

**Comment by dariavladykina** [comment]
It seems that if this can really help some writers to check and update their images from release to release, it wouldn't hurt to add this recommendation.

**Comment by cwickert** [comment]
I was the one who initially brought this up, but frankly speaking I'm no longer convinced. After one or two releases, guide maintainers know what to update or not. Tagging images only adds value if we have a tool an easy way to check them, say with a script. 

So unless someone comes up with a technical solution for checking, this should be optional.

**Comment by cwickert** [comment]
I decided to close this.
1. As long as we have no tooling to check for the image role automatically (say with `daps images`), it does not make much sense.
2. We would have to add necessary the tags to 500+ images in doc-sle alone. Realistically speaking, this is not going to happen.
