### ISSUE TITLE
Alphabetise sections in chapter 6, Structure and markup

### ISSUE THREAD

**Issue by tahliar** [SUSE/doc-styleguide#169]
Sometimes it's harder to quickly find something because not everything is in alphabetical order.

I could Ctrl+F but it's probably still good to alphabetise.

**Comment by dariavladykina** [comment]
Only "References to other external resources" fall out of the alphabetical order in this section, to be changed soon.

**Comment by dariavladykina** [comment]
Closing the issue as this has been merged.
