### ISSUE TITLE
Revise sudo recommendation

### ISSUE THREAD

**Issue by cwickert** [SUSE/doc-styleguide#172]
In the [prompts section](https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-prompt), we advise:

> Avoid using root prompts in your documentation by using the `sudo`  command where applicable.

This is very vague and would need some clarification, e.g. how many consecutive commands with root privileges are required before logging in as root or `su`-ing becomes easier.

However, instead of clarifying the `sudo` recommendation, I suggest to drop it altogether.

* unlike Ubuntu, SUSE does configure and use the root account
* we cannot be sure about a systems `sudo` configuration
* with containers, immutable root file systems, and alike, more and more machines don't have any users one could `sudo` from.

**Comment by sknorr** [comment]
> This is very vague and would need some clarification, e.g. how many consecutive commands with root privileges are required before logging in as root or `su`-ing becomes easier.

I don't think we need quite that level of detail. The idea with using sudo is that it _automatically_ drops you down to reduced permissions after executing a command. Having to type those 5 additional characters also make it clear each time that you're requesting elevated permissions.

Telling people to su their way through their (traditional, non-containerized) system is imo a general non-goal and does not depend on whether it's easy or not.

>     * unlike Ubuntu, SUSE does configure and use the root account

I don't really see this argument going anywhere -- yes, you can use the root account by default, but sudo is still a bit safer.


>     * we cannot be sure about a systems `sudo` configuration

It's Linux, you can never be sure of any configuration anyway. I trust that people who have a non-standard sudo setup will know how to perform the equivalent of running sudo on their non-standard systems, even if the docs tell them to use sudo.


>     * with containers, immutable root file systems, and alike, more and more machines don't have any users one could `sudo` from.

So, I think this is the heart of the issue ...
* within containers, you are root by default, but you can create new restricted users as you like (but it's probably not the most useful endeavor)
* I know nothing about MicroOS/immutability (at least nothing beyond the marketing prospectus), so I am not sure what the issue with it is.

I think there are a few other things to consider:

* Adding `sudo ` before each command makes it longer.
* Adding `sudo` generally does not hurt (unless it's not installed at all--which I think is not the case anywhere by default(?)). It may be useless if you're already on an account with elevated permissions.
* You never really know if someone is using the root account all the time anyway.
* `sudo` is another way to communicate "you need elevated permissions"

**Comment by sknorr** [comment]
another concern, via @lproven : 

* using sudo also adds some some logging.

**Comment by cwickert** [comment]
> another concern, via @lproven :
> 
>     * using sudo also adds some some logging.

No it doesn't, at least not in our default configuration.

**Comment by janajaeger** [comment]
With Stefan on this one.
