### ISSUE TITLE
Enable translations for comments in screens?

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#175]
In some cases, config file examples are reproduced as a whole or in part within our documentation. Config files often include comments on the usage of particular options. As @PadraigDillon1 mentioned, we currently treat screens as untranslatable in their entirety. In this case, this may be rather unhelpful/limiting the usefulness of the translations.

However, rather than thinking about making parts of screens translatable, we could also add a stricter rule about using callouts which are automatically translatable. However, use of callouts has other disadvantages, such as making it harder to copy-paste
a config file example (user view). It also makes it impossible to just drop in the file as-is into the `xml/` dir and XInclude it as plain-text, because plain-text does not support callouts (author view).

---

As an example, I've included part of my `/etc/chrony.conf` to highlight some things that we should think about in this context

```
# Record the rate at which the system clock gains/losses time. [1]
driftfile /var/lib/chrony/drift

# Allow the system clock to be stepped in the first three updates [2]
# if its offset is larger than 1 second.
makestep 1.0 3

# Enable hardware timestamping on all interfaces that support it. [3]
#hwtimestamp *

# Also include any directives found in configuration files in /etc/chrony.d [4]
include /etc/chrony.d/*.conf
```

1. Depending on the config file, comments may be marked with `#` or `//` or `<!--` etc. -- this character should not be translatable.
2. Comments can be multiple lines long. From the translator POV, this will be confusing as their tools are not made for working with sentences split across 72-/80-character lines. From our POV, we actually want to keep the line length to avoid display issues.
3. The option itself may be commented and should not be translated. I.e. you'd actually need a writer to make an informed decision which parts should be translated and which should not be
4. There may be untranslatable parts of the comment itself, such as the path in this example. However, this may be even trickier/harder to see if the name of the option being explained is being mentioned.

**Comment by janajaeger** [comment]
I am all for leaving it alone and keeping the code segments as they are. Any "solution"  to this reeks of overkill.

**Comment by cwickert** [comment]
DO NOT TOUCH SCREENS!
