### ISSUE TITLE
A definition of what's worthy of inclusion in docs

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#177]
Within the SUSE docs context, we have been making decisions about content worthy of inclusion largely based upon the input from product managers and based on internal feature requests/bug reports.

The new openSUSE documentation effort has started to define this for their own use cases in https://github.com/openSUSE/openSUSE-docs-revamped-temp/issues/27 (Adrien has reported that our style guide did not help him much ... and I see why).

Given the recent added community focus, potentially more direct customer interaction, and at times PMs arguing about such amongst themselves too, defining such criteria may also be helpful to us.

Ftr, we do have a stub section on this: https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-content

**Comment by janajaeger** [comment]
I think this is a non-issue. The customer interaction and focus shift haven't happened and we still go by feature requests and analytics. I would just close this.
