### ISSUE TITLE
Add information about use of info elements

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#18]
`<info/>` elements are not described...

**Comment by janajaeger** [comment]
I suggest we postpone this until we have consolidated the whole metdadata stuff. Then we can address both all the metadata and the info element which contains all the metadata.

**Comment by janajaeger** [comment]
Just a heads-up from the metadata and template front. We aren't heavy users of info anyway. In some places, meta doesn't work without them, in some it does. I cannot make up my mind whether we really need to add this here or whether info should just be something that is there in file templates and that authors rarely, if ever, have to add  themselves. In that case, we don't need to describe info, I'd say.
