### ISSUE TITLE
Mention titlecaseconverter?

### ISSUE THREAD

**Issue by tomschr** [SUSE/doc-styleguide#180]
As mentioned in our todays doc meeting, Christoph presented https://titlecaseconverter.com.

Maybe worth to add it as link into [5.3.2 Document titles: title-style capitalization](https://documentation.suse.com/style/current/single-html/docu_styleguide_with_changes/#sec-capitalization-title)?

**Comment by janajaeger** [comment]
Nice little tool :) Should we link to an external tool that at one point in time might just go away, though?

**Comment by dariavladykina** [comment]
We require title case capitalization in main titles of books and articles, and everywhere else it is sentence case. Therefore, not much work for the tool. But we are happy to recommend it if someone finds it useful.
