### ISSUE TITLE
Fix example of an abstract in the book outline

### ISSUE THREAD

**Issue by janajaeger** [SUSE/doc-styleguide#185]
We have updated the character limits for the abstract, but the example listed right below does not adhere to that and has still over 300 characters.

**Comment by dariavladykina** [comment]
We can borrow the example from here:
https://documentation.suse.com/kiwi/9/html/kiwi/contributing.html
The first one will do.

**Comment by janajaeger** [comment]
I would disagree. The "In this chaper, you learn to ..." or "This document describes" is pretty unnecessary IMHO and wastes precious characters. I think Christoph accepted the challenge to write short and snappy abstracts a while ago. Maybe check with him.

**Comment by dariavladykina** [comment]
Suggestion (from Brandon's message on SEO):

Perform an upgrade of a SUSE Linux Enterprise system to a new major version in environments which do not allow for standard booting of the installation.

**Comment by dariavladykina** [comment]
The paragraph about the Abstract is featured twice in the style guide.

Suggestion: Remove the second instance from the section "Chapters".

**Comment by janajaeger** [comment]
I would like to disagree again. The first instance covers things on the book level and the second on the chapter level. I'd not use the example with the second instance, but otherwise keep it around.
