### ISSUE TITLE
Define spelling for 'crashdump' (one words, two words)?

### ISSUE THREAD

**Issue by taroth21** [SUSE/doc-styleguide#188]
How do we want to spell 'crashdump'? (one word, two words?) While running a daps spellcheck I stumbled across those two different spellings. Iit seems that 'crashdump' is used in messages from the system, but we seem to spell it in two words within our texts otherwise (grepping in `doc-sle` gives me 9 hits for 'crash dump' as opposed to 3 hits for 'crashdump', of which 2 are system messages)

**Comment by dariavladykina** [comment]
Microsoft uses 'crash dump' https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps
Citrix uses 'crashdump' https://support.citrix.com/article/CTX221176

In Google, 'crash dump' gets 32 million more hits than 'crashdump' so I'd go with '**crash dump**'.

**Comment by dariavladykina** [comment]
Closing the issue as this has been merged.
