### ISSUE TITLE
New term: whitespace vs. white space

### ISSUE THREAD

**Issue by cwickert** [SUSE/doc-styleguide#189]
We currently have both "whitespace" and "white space" in our documentation. We should unify this and add it to the terminology table.

```
cwickert@linux:~/git/github.com/suse/doc-sle> grep "white space" xml/*
xml/deployment_boot_parameters.xml:      (with trailing white space) for the system default.
xml/deployment_prep_zseries.xml:       (with trailing white space) for the system default.
xml/deployment_prep_zseries.xml:    adding white spaces, therefore the last character (79) of each line needs
xml/net_yast.xml:      Search</guimenu> is used, separate domains with commas or white space.
xml/storage_filesystems.xml:        following line (mind the leading white space):
cwickert@linux:~/git/github.com/suse/doc-sle> grep "whitespace" xml/*
xml/apparmor_profiles.xml:     execute). A whitespace of any kind (spaces or tabs) can precede the
xml/apparmor_profiles.xml:    whitespace, it must be quoted. If the name begins with a
xml/apparmor_profiles.xml:   (<literal>##include</literal> is a comment) and there is no whitespace
xml/ay_networking.xml:  basename of the first whitespace-separated word is taken and these
xml/bootconcept.xml:         and add the following line (mind the leading whitespace):
xml/common_intro_available_doc_i.xml:      moving them to separate lines would create a whitespace before
xml/gnome_custom.xml:        may have a lot of whitespace at the beginning; they are not empty so keep 
xml/pv2fv.xml:       below (mind the leading whitespace):
xml/storage_multipath.xml:      the following line (mind the leading whitespace):
xml/tuning_logfiles.xml:       in the configuration file as long as the first non-whitespace character on the
xml/zypper.xml:<!-- cwickert 2018-11-19: No whitespace and no line break with indention
xml/zypper.xml:    between the phrases, otherwise there will be a trailing whitespace in the
```

'whitespace' is more popular and IHMO correct, but we better check.

**Comment by dariavladykina** [comment]
Merriam-Webster suggests 'white space'. However, according to some sources, this is not an inclusive term, and we may need to replace it with 'empty space'.

**Comment by cwickert** [comment]
I won't say Merriam Webster is wrong but referring to something different. It's definition "[the areas of a page without print or pictures](https://www.merriam-webster.com/dictionary/white%20space)" is generic, but we usually refer to the [special meaning in IT or programing](https://en.wikipedia.org/wiki/Whitespace_character), where it's common terminology. CSS for example has a `white-space` property, Unicode has `WSpace=Y` and `WS`.

And even though I consider inclusiveness important, I think the same goes for "blank space". It's a [generic term in punctuation, _any_ space between words](https://en.wikipedia.org/wiki/Space_(punctuation)), but we might need something more specific in our docs. Also, I don't see why `whitespace` would be considered not inclusive. It's not like whitelist vs. blacklist, where one is good and the other bad. While "white" might not be correct technically (depending on the stylesheet, it might very well be green or yellow), but I think the word is politically incorrect _per se_.



I see two options here, both have their pros and cons:

1. `whitespace` is more common and more specific, but prone to misspellings.
2. `blank space` is generic but resolves the spelling problem (there is no `blankspace`). AFAICS it should do for most occurrences listed above, but "whitespace-separated word" or "non-whitespace character" would need rephrasing.

@dariavladykina, please add this to the agenda of our next meeting.

**Comment by janajaeger** [comment]
Please, let's not bring up the inclusive thing into this discussion. White space is white in that it has no color. Nothing good or bad about that.

**Comment by dariavladykina** [comment]
I hate to bring it up myself, but it's in the Tier 1 list in our adopted [recommendations](https://inclusivenaming.org/word-lists/tier-1/) :-(

**Comment by dariavladykina** [comment]
The committee agreed on `whitespace`, it will be added to terminology.

**Comment by dariavladykina** [comment]
Term added - issue closed.
