### ISSUE TITLE
Terminology: form v/ dialog

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#19]
We should probably define form versus dialog.

**Comment by dariavladykina** [comment]
- [online] form
-A window or screen that contains numerous fields, or spaces to enter data

- dialog [box]
A window (= a separate area on a computer screen) that appears and gives the user information about what they are doing

Some insights on this:

https://www.collinsdictionary.com/us/dictionary/english/dialogue-box

https://dictionary.cambridge.org/dictionary/english/dialog-box

https://www.techopedia.com/definition/4661/form-databases

https://www.w3computing.com/vb2008/vb-forms-versus-dialog-boxes

**Comment by jfaltenbacher** [comment]
I checked MS terminology database and found these definitions:

**form**: In some applications (especially databases), a structured window, box, or other self-contained element that serves as a visual filter for the underlying data it is presenting.

**dialog box**: A secondary window that allows users to perform a command, asks users a question, or provides users with information or progress feedback.

Also see: https://www.microsoft.com/en-us/language

**Comment by dariavladykina** [comment]
A new compilation of terms: 

- **form** 
A structured window, box, or screen that contains numerous fields or spaces to enter data

- **dialog box** 
A secondary window that gives users progress feedback, prompts users to perform a command, enter information or select an option

**Comment by jfaltenbacher** [comment]
LGTM :)

**Comment by janajaeger** [comment]
I like your suggestion, @dariavladykina LVGTM!

**Comment by cwickert** [comment]
LGTM, except I'd remove the "box" to not introduce yet another term we need to explain.

**Comment by dariavladykina** [comment]
> LGTM, except I'd remove the "box" to not introduce yet another term we need to explain.

Remove the 'box' from 'dialog box'?

**Comment by dariavladykina** [comment]
Term added = issue closed.
