### ISSUE TITLE
new term: toolchain / tool chain

### ISSUE THREAD

**Issue by keichwa** [SUSE/doc-styleguide#2]
On SLE 12, we now have a "Toolchain Module" (containing GCC and compiler tools).

One or two words?

**Comment by sknorr** [comment]
So far, I've only ever seen this as a single words. There is no Merriam-Webster entry (at least not online). There is a Wikipedia entry called [Toolchain](en.wikipedia.org/wiki/Toolchain). The spelling as a single word also conveniently matches strings in the software itself.

Concluding, I think we should add the entry "toolchain" to the Terminology list.

**Comment by sknorr** [comment]
Fixed with 7a5af9ef5961406262fc4d383241917e40d83356
