### ISSUE TITLE
Mention the package tag in the style guide

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#20]
@taroth21 rightfully remarked that we should mention that we are using the `<package/>` tag for RPMs (etc.).

**Comment by dariavladykina** [comment]
From what I can see in `doc-sle`, we use `<command>rpm</command>`. Do we need to use `<package>` for RPM and when? 
We do have `<package>` listed among tags.

**Comment by jfaltenbacher** [comment]
I'd say listing in the docbook tag allow list is sufficient

**Comment by cwickert** [comment]
`<package>` should replace `<systemitem class="package">` and <systemitem class="resource">. IIRC we had the latter two documented in the style guide, but it seems it got lost somewhere.
