### ISSUE TITLE
Creating SP-independent links to documentation

### ISSUE THREAD

**Issue by dariavladykina** [SUSE/doc-styleguide#200]
Add the instruction to the "Structure and Markup" section of the style guide.

Rationale: When you create a link to documentation.suse.com, you insert the SP. However, sometimes there is the need NOT to link to a specific SP, but just general SLE 12/15 (the SP doesn't matter). To not be forced to use SP3 (which will be outdated at some time), we have a way to create a SP-independent link. You use just d.s.c/sle-15/YOUR_BOOK and it redirects to the latest SP automatically.

The underlying discussion here: https://suse.slack.com/archives/C02DR0BQ9C0/p1651566090157049

Suggestion of the content to add:

When there is no need to refer to the URL of a specific service pack within SUSE documentation, use generic links that point to the latest published documentation version of a book, section or chapter. Create a service pack-independent link with the following syntax: documentation.suse.com/sles/YOUR_BOOK. Use the (multipage) HTML format rather than single-html. For example, https://documentation.suse.com/sles/html/SLES-all/book-administration.html.

**Comment by tomschr** [comment]
I would suggest to create a new section (e.g. "External links to SUSE documentation") and add it before or after [Section 8, External links](https://susedoc.github.io/doc-styleguide/main/html/style-guide/index.html#sec-link) of our styleguide.

Reasons:

* Section 8 is a general section for any external links.
* A new section can just focus on the specifics of SUSE doc links
* We don't mix general linking with SUSE

**Comment by dariavladykina** [comment]
How about adding a paragraph at the end of [Section 8, External links](https://susedoc.github.io/doc-styleguide/main/html/style-guide/index.html#sec-link) in the form of a 'Note'? There is too little information for a separate section.

**Comment by tomschr** [comment]
@dariavladykina Depending on the level of detail, I'm not sure if a note would be enough. :thinking: 

For example, IMHO we should add the reasons and the syntax why to use "SP-independent linking". Sure, you could put that into a note, but I fear it would be a) too packed, and b) can be overlooked.

For that reasons, I would advocate for a separate section. Here is a very rough snippet what I would envision in such a section:

```
# External links to SUSE documentation

There can be reasons why you need a link which is independent from any SP:

* Your linked information is independent from any SP.
* You cannot, don't need or want to pick a specific SP.
* You want to link to the most recent SP without the need to think about next time.
* You want to support SEO that the most prominent SP is more important than previous, older SPs.
* <!-- add more reasons -->

Make sure to follow this syntax:

    d.s.com/<PRODUCT>[/<MAJOR_RELEASE>]/<DEEP_LINK>

The placeholders mean the following:

* PRODUCT: the abbreviation of the product, like "sle" for SUSE Linux Enterprise Server, "sle-ha" for SUSE Linux Enterprise Server High Availability Extension etc.
* MAJOR_RELEASE: an optional major release like 12 or 15.
* DEEP_LINK: the link that points to your specific chapter or section within a book. Make sure you see "html" and not "single-html". This is needed for SEO reasons.

For example, the link https://documentation.suse.com/sle-ha/15-SP3/html/SLE-HA-all/article-installation.html#sec-ha-inst-quick-req points to the "System requirements" for SLEHA. To turn this link into a SP-independent link, you need to identify the different components first:

* PRODUCT is "sle-ha"
* MAJOR_RELEASE is 15 (we don't want the SP, remember?)
* DEEP_LINK is /html/SLE-HA-all/article-installation.html#sec-ha-inst-quick-req

To assemble this together, we can use the following links:

* https://documentation.suse.com/sle-ha/15/html/SLE-HA-all/article-installation.html#sec-ha-inst-quick-req
  Redirects to the most recent SP for the major release 15
* https://documentation.suse.com/sle-ha-15/html/SLE-HA-all/article-installation.html#sec-ha-inst-quick-req
  Does the same, but without a slash but using a dash
* https://documentation.suse.com/sle-ha/html/SLE-HA-all/article-installation.html#sec-ha-inst-quick-req
  Redirects to the most recent major release

The redirection rules on d.s.c will point to the most recent version.

If IDs have been changed between releases or SPs, this is what happens:

* If the hash part (everything after #) is not found, the browser will jump to beginning of the file
* If the file cannot be found (in our example article-installation.html) the server will respond with a 404 error (file not found).
```

The wording and structure has to be improved, but that's the general idea.

The styleguide commitee should decide or recommend:

* if we prefer slashes over dashes?
* how deep we should go?
* any other recommendations, tips, or what we should avoid

Does that make sense?

**Comment by taroth21** [comment]
Hi all, could we perhaps cover the following 3 use cases that Frank outlined in the discussion yesterday?

- /sles/ redirects to the latest SLES release (regardless of the major version), highest SP available
- /sles-12/ redirects to the latest SLE 12 SP
- /sles-15/ redirects to the latest SLE 15 SP

The general approach is the same: Sometimes it makes sense not to link to a specific SP, but to the latest version per se or the latest version within a specific codestream.

**Comment by dariavladykina** [comment]
Hi all, if we have decided to have a longer section to explain the details, then I'll work on Toms' draft. I think the 3 use cases by Frank are already described there.

I would go with the dash instead of the slash. It is a bit easier to read without at least one extra slash.
