### ISSUE TITLE
Do not use any version numbers in titles

### ISSUE THREAD

**Issue by taroth21** [SUSE/doc-styleguide#201]
Please add this to the Style Guide as numbers in titles make it hard to compare data with Google Analytics. In some cases version numbers are needed (e.g. Upgrade Guide or chapters related to upgrades) sometimes need to mention version numbers in titles (e.g. Upgrading from SLE 15 SP1 to SLE 15 SP2).

**Comment by dariavladykina** [comment]
This applies to book titles and chapter titles.
Version numbers in titles make it hard to run comparable analytics. 
Sections should still be allowed to carry version numbers and even some chapters when there would be no way of avoiding it (Upgrade docs for example)

**Comment by dariavladykina** [comment]
Closing the issue as this has been merged.
