### ISSUE TITLE
File system names

### ISSUE THREAD

**Issue by cwickert** [SUSE/doc-styleguide#207]
When I looked over proofing-changes in https://github.com/SUSE/doc-sle/commit/52e3d029408f7a2a20361471775f4c9c2d84e8c7 I noticed that occurrences of `ext4` have been changed into `Ext4`. IHMO this is wrong because the name of the file system is ext4, see https://en.wikipedia.org/wiki/Ext4.

We are currently capitalized in texts and lowercase in screens and commands.

```
cwickert@localhost:~/git/github.com/suse/doc-sle> grep -E "ext2|ext3|ext4" xml/* | wc -l
87
cwickert@localhost:~/git/github.com/suse/doc-sle> grep -E "Ext2|Ext3|Ext4" xml/* | wc -l
129
```

IHMO we use only lowercase. It's not only the correct term but also makes usage in texts and commands/screens consistent.

This probably applies to other file systems as well: Btrfs, ReiserFS, XFS, cramfs, ... you name it. All of them should be in the style guide. Note that some of these names are capitalized, upper or camel case, so we won't achieve full consistency (commands are often are lowercase despite the official name), but we would be consistent in so far as we use the official names/spellings.

**Comment by dariavladykina** [comment]
This is what we have in the style guide now: "use this capitalization for all versions of the Ext file system standard; intentionally
inconsistent with project standard to emphasize that this is a proper name". There was a certain logic when this was standardized by the doc team. 
I think there should be a broader discussion within the team as to updating this to lower case.

**Comment by cwickert** [comment]
Committee agreed to follow upstream project names instead of some "intentionally inconsistent" name.

**Comment by cwickert** [comment]
Action item for @cwickert: compile a list of file system names and spellings.

**Comment by cwickert** [comment]
And now for the list:

# Supported file systems
Btrfs: pronounced as "better F S", "butter F S" or simply by spelling it out, default file system in SUSE Linux Enterprise
ext2: file system for Linux, mostly replaced by ext3 and ext4
ext3: journaled file system for Linux
ext4: journaled file system for Linux, successor of ext3
FAT (File Allocation Table): default file system for MS-DOS, still used for EFI partitions
FAT12: variant of FAT
FAT16: variant of FAT
FAT32: variant of FAT
ISO 9660: file system for optical disc media such as CD-ROMs
SquashFS: compressed read-only file system for Linux
UDF (Universal Disk Format): file system for optical disc media, supplants ISO 9660 on DVDs
UFS (Unix file system): family of file systems used by BSD, SunOS, and NextStep
VFAT: extension for long file names on FAT file systems
XFS: journaled file system, default in RHEL

# [Unsupported](https://susedoc.github.io/doc-sle/main/single-html/SLES-storage/#sec-blacklist-filsystem) file systems
ADFS (Advanced Disc Filing System): file system for RISC OS
AFFS (Amiga Fast File System): file system for Amiga
BeFS (Be File System): file system for BeOS
BFS: file system for SCO UnixWare OS
CramFS (Compressed ROM/RAM File System): read-only file system for Linux, replaced by SquashFS
EFS (Encrypting File System): filesystem encryption for NTFS 3.0
EROFS (Enhanced Read-Only File System): read-only file system for the Linux kernel
EXOFS (EXtended Object File System):  object-based file system, removed from the Linux Kernel 5.1
VxFS (Veritas File System): file system for Sun Solaris or HP-UX
HFS (Hierarchical File System): file system for IBM's MVS/ESA/SP through z/OS operating systems, no longer used as of 2021
HPFS (High Performance File System): file system for OS/2
JFS (Journaled File System): journaling file system for AIX, OS/2, eComStation, and ArcaOS, developed by IBM
MINIX: file system for the Minix operating system
NILFS2 (New Implementation of a Log-structured File System): log-structured file system for Linux, developed by NTT
NTFS (New Technology File System): journaling file system for Windows, developed by Microsoft
OMFS (Optimized MPEG Filesystem): file system created by SonicBlue for use in DVR and MP3 players
QNX4: Extent-based POSIX file system for QNX
QNX6: Extent-based POSIX file system for QNX >= 6.4
System V FS: file system for UNIX System V, developed by AT&T, replaced by UFS
UFS (Unix File System): file system for System V, replaced System V FS.

# Other important terms
EFI: Extensible Firmware Interface
MBR: master boot record
LVM: logical volume management
RAID: Redundant Array of Independent Disks
UEFI: Unified Extensible Firmware Interface, successor of EFI

See also: More info: https://www.man7.org/linux/man-pages/man5/filesystems.5.html

**Comment by dariavladykina** [comment]
All relevant items have been added to TermWeb, closing this issue.
