### ISSUE TITLE
Maintain releases

### ISSUE THREAD

**Issue by tomschr** [SUSE/doc-styleguide#215]
# Problem

Every open source project, be it software or documentation, improves over time and creates new releases. As a best practice, every release should contain a list of changes that describes the improvements from the previous release. Usually we create a Changelog for this.

However, our doc-styleguide has tags, but no releases. I think, it is a drawback or an omission and should be changed. I see this problems:

* A reader who has opened this GitHub project has to find the rendered HTML, click the right section inside the HTML and find the relevant part that fits to the release in question. This is a detour and it's annoying.
* Although we have a kind of "changelog", it's written in XML and hidden in the `xml` folder. From a quick glance, it's not obvious from outside. Furthermore, you need (again) the HTML to read it.
* Even if the reader finds the HTML, it's a _summary_. Stripped down to the most important changes. However, sometimes, we need the full list.
* IMHO, projects should consider releases also as a good release management, as an advertisiment tool, and as a way to tell the public, "hey, we are alive and have created a new release!". At the moment, it's not visible.

In this case, the releases is **not about downloading the sources**. Of course, you can, but IMHO it's secondary. This issue is about to have a release to **showcase our project, improve visibility**, to see that we care, and are proud of showing the changes.

Personally, I believe every project should have a release.

# Suggestion

A good release solves all of the above issues. Plus it comes with some benefits:

* Easy to see the full diff by clicking the "Full changelog" link.
* Easy to compare it against the last release. 
* Available from the main project page; one click and you see the latest release.
* Praises our contributors.
* Mark a release as "pre-release"
* Upload additional files. For example, we could upload the HTML pages if we wanted.
* It's not a contradiction to have a "changelog" in XML inside our style guide and a detailed changelog on GitHub. It's easy to add the link to the detailed view into our XML.

The nice thing is, you don't really need much work as GitHub supports you with it in an automated way. It's done in 1-2min, even less.

To create a new release for doc-styleguide, use the following steps:

1. Open https://github.com/SUSE/doc-styleguide/releases.
1. Click the green "Create new release" button.
1. Choose a tag from the pull-down menu.
1. Enter a release title (you can repeat the tag name).
1. Click the grey "Generate release notes" button. GitHub creates a list of changes from its pull requests automatically. It adds also contributors, if needed. Of course you can edit the text if you want and add additional entries.
1. Review the output. Click the "Preview" tab to get a nice rendered view.
1. When satisfied, click the green "Publish release" button.

Done.

**Comment by dariavladykina** [comment]
Thank you @tomschr, this is well accepted. Closing the issue now.
