### ISSUE TITLE
Prefer HTTPS

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#22]
We should add a hint that we prefer HTTPS links over plain HTTP. Not quite sure what section to put this in -- possibly structure, near `<link/>` tag description.
- [ ] Mention as a rule
- [ ] Make sure we use as many HTTPS links as possible ourselves

**Comment by janajaeger** [comment]
Is this really necessary? The world has moved on since 2016. There aren't many http left on the internet. Don't bloat the Style Guide with applications of common sense, I'd say.

**Comment by jfaltenbacher** [comment]
agree with Jana, nevertheless, we could add a short line to the docbook tag allow list where <link> is listed

**Comment by dariavladykina** [comment]
Closing as the update has been merged.
