### ISSUE TITLE
Passthrough or pass-through?

### ISSUE THREAD

**Issue by dariavladykina** [SUSE/doc-styleguide#226]
Not a big deal but would be nice to have unified spelling. 
We currently have 56 pass-through vs 58 passthrough occurrences in `doc-sle`.
 
[Google Trends](https://trends.google.com/trends/explore?date=today%205-y&q=USB%20pass-through,USB%20passthrough), for example, shows more interest for 'passthrough'.

Shall we just agree on one variant and keep to this spelling? I'm in favor of 'passthrough'.

**Comment by dariavladykina** [comment]
`pass-through` according to MW

**Comment by jfaltenbacher** [comment]
added to TermWeb

**Comment by dariavladykina** [comment]
Reopening as the term seems to have disappeared from TermWeb :-(

**Comment by jfaltenbacher** [comment]
HI @dariavladykina the entry for passthrough is still there. I moved it to the 'needs translation' section so that it would be picked up with the next translation round. After translation, the entry will be moved back to the public section

**Comment by dariavladykina** [comment]
Thanks @jfaltenbacher, I'll close it again then :-)
