### ISSUE TITLE
Date and Time - ISO 8601

### ISSUE THREAD

**Issue by keichwa** [SUSE/doc-styleguide#228]
I think we need a statement about Date and Time.  My wish is that we make use of the ISO 8601 standard.  See
https://en.wikipedia.org/wiki/ISO_8601.

At the end of the abstract you write:
```
Publication Date: 08/05/2022
```
In an international context, this is ambiguous.  Better either say `2022-08-05` (and mention in the "conventions" part of the document that we follow ISO 8601) or write `5 August 2022` or `August 5, 2022` or `August 5th, 2022`.  You'll probably see the point `;)`.

**Comment by janajaeger** [comment]
I think this is being discussed with Joseph anyway. It came up during the portal and metadata discussions. Before we rush to any recommendations, we should check with Toms/Joseph on how far along they on the standardization efforts.

**Comment by PadraigDillon1** [comment]
Will any date and time format be internationalized to allow different formats by language?

**Comment by janajaeger** [comment]
> Will any date and time format be internationalized to allow different formats by language?

I don't think so, actually. This info needs to be processed by the portal scripts to build lists of new articles. If we internationalized stuff here, we needed to adjust the scripts per language. We should check with Toms.

**Comment by cwickert** [comment]
![perfect-date-1](https://github.com/SUSE/doc-styleguide/assets/972070/59a46608-bcf0-437a-b982-b3f7123e0dc0)

**Comment by tomschr** [comment]
I agree with Karl and Christoph. Any date should be in ISO 8601 format (YYYY-MM-DD). This is also enforced/validated by GeekoDoc, for example, with `revision/date`.

The stylesheets expects ISO 8601 anyway. In the rare case that the date is incomplete (maybe YYYY-M or YYYY-MM or YYYY-M-D), the stylesheets take care of that and correct it to YYYY-MM-DD. But that's a minor implementation detail.

Regarding the portal discussion: In my humble opinion, this is a different topic. The portal should display a date in whatever format is requested. But this can only be done, if we recommend to a format. That can only be ISO 8601.

**Comment by tomschr** [comment]
> Will any date and time format be internationalized to allow different formats by language?

The DocBook stylesheets contain means of formatting a date for a specific language. For example, for German you have this entry:

https://github.com/docbook/xslt10-stylesheets/blob/efd62655c11cc8773708df7a843613fa1e932bf8/gentext/locale/de.xml#L594

**Comment by dariavladykina** [comment]
We are pretty sure the required format YYYY-MM-DD is implemented thanks to the style sheets, so closing this question.

**Comment by keichwa** [comment]
Daria Vladykina ***@***.***> writes:

> We are pretty sure the required format YYYY-MM-DD is implemented
> thanks to the style sheets, so closing this question.

Thanks for your support.  The question also is whether it recommended to
use it in English texts by default.

-- 
Karl Eichwalder
