### ISSUE TITLE
Live patch or livepatch?

### ISSUE THREAD

**Issue by dariavladykina** [SUSE/doc-styleguide#229]
In `doc-sle` we have 92 "live patches" and 21 "livepatches".
[Google Trends](https://trends.google.com/trends/explore?date=today%205-y&q=live%20patch,livepatch) also displays more interest in "live patch".

Shall we agree on one variant and keep to this spelling? My suggestion is "live patch".

**Comment by jfaltenbacher** [comment]
I am undecided but if we already have more _live patches_, I would stick with that

**Comment by PadraigDillon1** [comment]
I would lean towards 'Live Patch'.

**Comment by cwickert** [comment]
Definitely "live patch", that's what the technology and the module is called.

**Comment by cwickert** [comment]
No problem in doc-sle, "livepatch" (single word) is only used in xml:ids or file names.

**Comment by dariavladykina** [comment]
Added to TermWeb - closing
