### ISSUE TITLE
Auto login, autologin or auto-login?

### ISSUE THREAD

**Issue by dariavladykina** [SUSE/doc-styleguide#235]
Or "automatic login" altogether?

**Comment by dariavladykina** [comment]
Usage [trends](https://trends.google.com/trends/explore?date=today%205-y&q=auto-login,autologin,auto%20login)

**Comment by PadraigDillon1** [comment]
I don't have a fovourite but the trends analysis seems to show significant greater usage for 'auto login'. I'm good with that option.

**Comment by jfaltenbacher** [comment]
I also see more usage of 'auto login'

**Comment by dariavladykina** [comment]
Added to TermWeb, closing
