### ISSUE TITLE
split brain or split-brain

### ISSUE THREAD

**Issue by dariavladykina** [SUSE/doc-styleguide#236]
Found mainly in `doc-sleha`, this term is inconsistent at this point:
`split brain` = 26
`split-brain` = 14

[Google Trends](https://trends.google.com/trends/explore?date=today%205-y&q=split%20brain,split-brain) also show more interest in `split brain`.

What do you say, @tahliar ?

**Comment by tahliar** [comment]
I mostly see `split brain`, and I guess this is probably the official technical term. However, in the HA docs it usually appears in contexts like "a split brain scenario", in which case it should grammatically be `split-brain`. 

Google has just taught me that it's based on this medical term: https://www.sciencedirect.com/topics/neuroscience/split-brain

So I think we can probably follow the "noun = two words, adjective = hyphenated" rule (and I will need to fix that in the HA docs).

**Comment by dariavladykina** [comment]
Added to TermWeb
