### ISSUE TITLE
Only use "since" in temporal senses

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#25]
Brought up by @taroth21, like "once," "since" is also often used for reasonings. We might want to restrict it to its use in temporal senses.

**Comment by cwickert** [comment]
I consider this a minor improvement, but it makes sense.

If we add this to the Style Guide, we should make suggestions for alternatives ("because of", "due to").

**Comment by dariavladykina** [comment]
Do we want this? I'm not quite sure :-)

**Comment by PadraigDillon1** [comment]
I agree with this proposal. I like Christoph's proposals as improved alternatives.
