### ISSUE TITLE
[time-out] to timeout

### ISSUE THREAD

**Issue by dariavladykina** [SUSE/doc-styleguide#252]
Let's use `timeout` instead of `time-out` (recommended by MW).
`Timeout` is upstream terminology and e.g. `doc-sle` contains 121 instances (many of which are screens from upstream) against 9 instances of `time-out`.
Also, [Google Trends](https://trends.google.com/trends/explore?q=timeout,time-out&hl=en) are in favor.

**Comment by janajaeger** [comment]
Let's listen to Google Trend then ;) Timeout!

**Comment by PadraigDillon1** [comment]
Agreed... Timeout.
