### ISSUE TITLE
Screenshots with meaningful data?

### ISSUE THREAD

**Issue by cwickert** [SUSE/doc-styleguide#254]
The second rule in section [7.10.2 Screenshots](https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-screenshot) reads:

> Always create screenshots illustrating the situation right before an action has been taken.

This means I would have a screenshot of a YaST module after opening it but before entering any data. I don't think this makes sense. If we want the screenshot to offer some benefit, we should perform the necessary actions, means we enter enter data, select something, tick checkboxes etc. so all of this is shown in screenshot.

**Comment by jfaltenbacher** [comment]
I would guess, that the sentence means 'Take the screenshot before you click on OK/SAVE/NEXT'. 
This kind of information can be misunderstood in many ways.

Looking at MS style guide, they do not get into much detail here:
_Make sure the reader can get the whole story from either the picture or the written description._

**Comment by cwickert** [comment]
We discussed this again in the 2024-07-18 meeting and agree to not pursue this issue further. While we do think that meaningful data does add value, it adds to much hassle: Taking screenshots will be more work and data in the screenshots can easily become inconsistent if the text is touched. Not to mention localization (costs).
