### ISSUE TITLE
Remove tags and inline elements that are not used/needed

### ISSUE THREAD

**Issue by dariavladykina** [SUSE/doc-styleguide#256]
There is an idea conveyed by Frank, to trim down the list of XML tags and inline elements in our style guide, i.e. to get rid of those that are almost never used and/or can be replaced by others. 
Let's identify them!

**Comment by tomschr** [comment]
Do you mean the list from [section 8.1.4 Inline elements](https://documentation.suse.com/style/current/single-html/docu_styleguide/#id-1.10.7.5)?

I'm a bit confused what's the benefit of that idea? Shouldn't the table show all inline elements what GeekoDoc allows? We don't have such information elsewhere.

When GeekoDoc was created, it was already a trimmed down list from DocBook. Shouldn't the table reflects somehow what is allowed in GeekoDoc?

To get a better picture, I analyzed the occurrences of each inline tag. Click the arrow to see the details:

<details>
  <summary>List of inlines tag and their amount (doc-sle/main)</summary>

The table was generated with the following script. Keep in mind

```bash
for tag in citetitle co code command constant email emphasis envar filename function guimenu inlinemediaobject keycap keycombo link literal menuchoice option package parameter phrase productname prompt quote replaceable systemitem subscript superscript tag trademark uri varname xref; do
  quotedtag="\`$tag\`" 
  NR=$(egrep "<$tag" xml/*.{xml,ent} | wc --lines)
  printf '| %-20s| %10s |\n' $quotedtag $NR
done
```

| Tag           | Amount |
| ------------- | ------:|
| `citetitle`   |     92 |
| `code`        |      0 |
| `command`     |   5596 |
| `constant`    |      2 |
| `email`       |      4 |
| `emphasis`    |   1291 |
| `envar`       |    130 |
| `filename`    |   4008 |
| `function`    |      1 |
| `guimenu`     |   5139 |
| `inlinemediaobject`  | 11 |
| `keycap`      |    607 |
| `keycombo`    |    214 |
| `link`        |    791 |
| `literal`     |   6246 |
| `menuchoice`  |    413 |
| `option`      |   1714 |
| `package`     |    237 |
| `parameter`   |    115 |
| `phrase`      |    666 |
| `productname` |    258 |
| `prompt`      |     38 |
| `quote`       |    430 |
| `replaceable` |   2416 |
| `systemitem`  |   1754 |
| `subscript`   |      0 |
| `superscript` |     15 |
| `tag`         |    147 |
| `trademark`   |      1 |
| `uri`         |      3 |
| `varname`     |     37 |
| `xref`        |   2353 |
</details>

When you sort them you get these:

<details>
  <summary>Sorted tags by their occurances</summary>

This is the script that takes the list:

```bash
$ for tag in citetitle co code command constant email emphasis envar filename function guimenu inlinemediaobject keycap keycombo link literal menuchoice option package parameter phrase productname prompt quote replaceable systemitem subscript superscript tag trademark uri varname xref; do
  NR=$(egrep "<$tag" xml/*.{xml,ent} | wc --lines);
  echo "$NR $tag";
done | sort -nr
```

This is the result:

```
6331: co
6249: literal
5610: command
5148: guimenu
4013: filename
2421: replaceable
2361: xref
1774: systemitem
1717: option
1308: emphasis
801: link
680: phrase
607: keycap
430: quote
413: menuchoice
258: productname
238: package
214: keycombo
147: tag
138: citetitle
130: envar
115: parameter
47: prompt
37: varname
15: superscript
11: inlinemediaobject
4: trademark
4: email
3: uri
3: constant
1: function
0: subscript
0: code
```

</details>


As you can see, many tags are used. The only tags that are used a few times are:

* `uri` (3 times)
  I think this is still useful. Sometimes you need URIs/URLs which should NOT turn into clickable links.
* `constant` (3 times)
  Rarely used. It's probably debatable, when you use this tag.
* `trademark` (1)
  Although this tag is used only once (on the imprint page), we shouldn't remove it.
* `code` (0), `subscript` (0)
  Theoretically, these tags could be removed.
