### ISSUE TITLE
X.509

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#27]
could be added...

**Comment by janajaeger** [comment]
... or not?

**Comment by jfaltenbacher** [comment]
seems to be a certificate https://en.wikipedia.org/wiki/X.509

**Comment by dariavladykina** [comment]
Will be added to TermWeb.

**Comment by PadraigDillon1** [comment]
Here's a definition I found that could be used: X.509 is a standard format for public key certificates, digital documents that securely associate cryptographic key pairs with identities such as websites, individuals, or organizations. [X.509 certificates are used in many Internet protocols, including TLS/SSL, which is the basis for HTTPS, the secure protocol for browsing the web
