### ISSUE TITLE
[doc] Issue in "Language"

### ISSUE THREAD

**Issue by taroth21** [SUSE/doc-styleguide#282]
Language:

https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-language

'The correct spelling of SUSE product names is listed in the terminology table (Appendix A, Terminology and general vocabulary) and in the entities file of the Doc Kit repository at https://github.com/openSUSE/doc-kit/blob/main/docbook5-book/xml/generic-entities.ent.'

Two issues here:

- generic entity file in doc-kit has moved to https://github.com/openSUSE/doc-kit/blob/main/entities/generic-entities.ent now
- in the long run, we should probably refer to TermWeb for product names, no?

**Comment by dariavladykina** [comment]
Thanks Tanja, I'll update the entity file reference. 
As for a reference to TermWeb, there was a consultation with Legal who advised to not place a direct link to TermWeb in our style guide.

**Comment by dariavladykina** [comment]
Closing as the update has been merged.
