### ISSUE TITLE
Section "Entities" should also mention generic-entities.ent

### ISSUE THREAD

**Issue by tomschr** [SUSE/doc-styleguide#285]
# Situation

[Section 9.3 Entities](https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-entity) mentions the file `xml/entity-decl.ent`. However, in most repos we switched to `xml/generic-entities.ent` with the help of doc-kit.

# Proposal

I think, we should mention the file `xml/generic-entities.ent` in the styleguide. Probably something like the following could be enough:

```diff
-Find these entities in the file xml/entity-decl.ent in each documentation repository.
+Find these entities in the file entity-decl.ent or generic-entities.ent in each documentation repository.
```

## No xml directory
I would remove the directory (here `xml/`) and only show the entity filename. The reason for this  it's only valid for doc-sle, but not doc-modular.

## Additional idea
When you are over it and want to go an extra mile, maybe you could restructure the section a bit. One way to do it could be:

```
9.3 Entities
  Add the content of 9.3.2 Common types of entities here?

9.3.1 Variants of entity files
  * Explain the two variants of entity files (entity-decl.ent and generic-entities.ent).
  * Perhaps mention that generic-entities.ent is NOT allowed to be changed.
    Maybe it's enough to say, this file is modified outside of the
    repo (without mentioning the details)
  * Any changes should be added to product-entities.ent (or entity-decl.ent)

9.3.2 Using entity files
  * You probably need to show two examples how to include the entity file in the header
  * Example 29 is independent of the file and can be used.

9.3.3 Updating entity files
  * Probably only add this section, if you want to mention doc-kit.
  * You could mention which files can be modified and which not.
  * It's not really needed to add the complete procedure how to update the files.
    Maybe it's enough to refer to doc-kit
```

**Comment by dariavladykina** [comment]
Closing as this was resolved in #291
