### ISSUE TITLE
Add a section for conscious language  

### ISSUE THREAD

**Issue by Amrita42** [SUSE/doc-styleguide#286]
Do we need a section specific for conscious language , to avoid terms like master/slave or balcklist/whitelist and the prefered terms ind documentation (not source code)?

Similar to https://redhat-documentation.github.io/supplementary-style-guide/#conscious-language

**Comment by janajaeger** [comment]
We already have a stub on this: https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-bias which I personally find quite sufficient. We already have longish wordlist in the styleguide. No need to open yet another one. I bet, we are already paying attention to the rules maintaining the other wordlist?

**Comment by Amrita42** [comment]
Yes I am aware but I feel imo , instead of browsing through the entire inclusive naming link , it would be good to have at the least the main words  followed by a link .

**Comment by jfaltenbacher** [comment]
TermWeb also covers some of the inclusive naming recommendation, maybe an info to check in TW can be added to the style guide (in general, we could mention TW more often in the style guide as it is now available)

**Comment by dariavladykina** [comment]
@jfaltenbacher Shall I give the link to this address for TW? https://suse.termweb.eu/search/terms

**Comment by jfaltenbacher** [comment]
yes, great idea. The short form https://suse.termweb.eu/ should be sufficient. 
Maybe you need to add a note that this only works for SUSE employees and external partners with a SUSE account (https://www.suse.com/account/create/)

**Comment by Amrita42** [comment]
Just one query is here , our style guide is a public repository and TermWeb is like Julia mentioned private so should we adding a private link which is accessible.

**Comment by jfaltenbacher** [comment]
I believe it is sufficient to mention that visiting this link requires a SUSE account (which is available to all employees by default and can be requested for externals at https://www.suse.com/account/create/)

**Comment by dariavladykina** [comment]
Closing as the required changes were merged.
