### ISSUE TITLE
'Technology Preview' vs. 'Technical Preview'

### ISSUE THREAD

**Issue by cwickert** [SUSE/doc-styleguide#295]
TermWeb currently contains neither 'Technology Preview' nor 'Technical preview'. Both terms are in the Style Guide however, where ['Technology preview' is correct and 'Technical Preview' forbidden](https://documentation.suse.com/style/current/single-html/docu_styleguide/index.html#sec-terminology).

I'm afraid it's not that simple. :unamused: 

### Technology Preview ###

* used in documentation, [1100+ hits on documentation.suse.com](https://www.google.com/search?q=%22Technology++Preview%22+site%3Adocumentation.suse.com)
* we even have [a section called 'Technology Previews'](https://documentation.suse.com/sles/15-SP5/html/SLES-all/preface-deployment.html#id-1.4.2.6.6) in the preface of every guide.
*  the preface commonly shared among all guides, so 'Technology preview' is in [doc-kit](https://github.com/openSUSE/doc-kit/blob/main/docbook5-book/xml/common_intro_support.xml).

### Technical Preview ###

* only [14 hits on documentation.suse.com](https://www.google.com/search?q=%22Technical++Preview%22+site%3Adocumentation.suse.com), which boil down to 3 occurrences in the sources:
  * [a single occurrence of 'Technical Preview'](https://github.com/SUSE/doc-sle/blob/main/xml/ulp.xml) in a SLE Micro.
  * one is actually correct as it refers to "Windows Server 2016 Technical Preview". Obviously Microsoft is using 'Technical Preview', too. Same goes for Amazon, which then causes hits in the [Partner Certification & Solutions Catalog](https://www.suse.com/pcsc/viewVersionPage?versionID=23089)
  * one is from the SLE 12 SP5 Docker guide. It seems we used 'Technical Preview' in the past.
* used in https://www.suse.com/products/subscription_terms.pdf
* used in some release notes. More often than in the docs, but least frequent than 'technology preview'.
* used in support documents, both [update announcements](https://www.suse.com/support/update/announcement/2019/suse-ou-20192489-1/) and [knowledge base articles](https://www.suse.com/support/kb/doc/?id=000020592)
* [used by Rancher](https://www.suse.com/c/rancher_blog/rancher-desktop-v0-6-including-linux-tech-preview/)
* [used by some PMs](https://jira.suse.com/browse/PED-8022?focusedId=1332008&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1332008)

To make things worse, there are [blog posts](https://www.suse.com/c/sap-system-automation-that-fosters-innovation/) and [release notes](https://www.suse.com/releasenotes/x86_64/SUSE-Enterprise-Storage/3/index.html) that use both terms as synonyms.

Summary:
* I started at SUSE 8+ years ago and never used something other than 'technology preview', but we seem to have used 'technical preview' more often in the past before consolidating to 'technology preview' in the documentation.
* We should be consistent at least in the docs, ideally across the company. But who is to switch?
* 'Technology preview' is also used by Red Hat, Apple, Adobe while companies like Microsoft and Citrix use 'technical preview'.
* Overall, 'technical preview' is more popular on the web, but only slightly.

**Comment by dariavladykina** [comment]
Here is another discussion on this topic: https://suse.slack.com/archives/C0598MWD8DC/p1716873866761219

**Comment by dariavladykina** [comment]
In my opinion, the best way for us is to stick to what we already have in the majority of documents. We can cooperate with the Rancher team once we start working on the docs together. We probably cannot influence some other teams using the other term, 'technical preview'.
I can see 'technology preview' was entered into TermWeb and is now a draft.

**Comment by jfaltenbacher** [comment]
I am checking with Alex about her progress on this
https://suse.slack.com/archives/C0598MWD8DC/p1716873866761219

**Comment by jfaltenbacher** [comment]
the slide deck with final decision on 'Technology preview' was just published:
https://docs.google.com/presentation/d/1Y83USO5Z0i-at67ZbVuEvoUbIY9sYYeOFARN4Vc0HKM/edit#slide=id.g2f0285a6334_0_857

**Comment by dariavladykina** [comment]
Thanks @jfaltenbacher for adding this to TermWeb. Closing this issue now.
