### ISSUE TITLE
Increasing the Word Limit for Sentences

### ISSUE THREAD

**Issue by alexvonme** [SUSE/doc-styleguide#299]
This issue concerns the [Sentence structure](https://documentation.suse.com/style/current/single-html/docu_styleguide/index.html#sec-structure-sentence
) section.

May I ask if the word limit could be increased to 24 or 28 words? SUSE has one of the lowest word limits that I've come across, and I think this might be counterintuitive.

I'm the [GSoC](https://summerofcode.withgoogle.com/) student for [Kanidm](https://github.com/kanidm/kanidm) where under my mentor @firstyear, I'm trying to improve the documentation. Kanidm is under the openSUSE project, and we are planning to standardize the [documentation](https://kanidm.github.io/kanidm/stable/) in line with the SUSE style guide. To do so, I hope to improve the vale style guide, which we were aiming to adopt. Just today, I submitted a pull request (openSUSE/suse-vale-styleguide#95) to check for sentence length.

However, the 20-word limit for each sentence simply doesn't work well with a network-related software like Kanidm.

To illustrate with an example, the [RADIUS section](https://kanidm.github.io/kanidm/stable/integrations/radius.html) of the documentation starts with the following sentence:

``Remote Authentication Dial In User Service (RADIUS) is a network protocol that is commonly used to authenticate Wi-Fi devices or Virtual Private Networks (VPNs).
``

This sentence is "clear and direct", as suggested, but because it mentions networking tools, it is above 20 words. Apart from abbreviation explanations, there are also a lot of multi-word phrases such as "host name" and "end user". Furthermore, as an identity management server, Kanidm has to often explain its functions. At least, to a point that doesn't limit its user base to senior developers with extensive experience.

**Comment by dariavladykina** [comment]
I did a research on tech writing resources: 
Some of them confirm our stance be recommending up to 20 words: [MDN](https://developer.mozilla.org/en-US/blog/technical-writing/) or [Proxmox](https://pve.proxmox.com/wiki/Technical_Writing_Style_Guide#:~:text=Sentence%20length,-Use%20short%20sentences&text=In%20general%2C%20an%20average%20of,%2C%20read%2C%20and%20understand%20information.)
Some agree on 25 words, like [here](https://www.enago.com/academy/how-to-optimize-sentence-length-in-academic-writing/).
Some allow up to 30 words: [MIT](https://web.mit.edu/juggler/www/ocw/ocw_lectures/class01/lecture_shorten_sentences.htm)

**Comment by alexvonme** [comment]
Some additional examples are:
GitLab -  [In internal Vale rule](https://docs.gitlab.com/ee/development/documentation/styleguide/index.html#language) - 25
Datadog - [In internal Vale rule](https://github.com/DataDog/datadog-vale/blob/main/styles/Datadog/sentencelength.yml) - 25
Google - [Style Guide](https://developers.google.com/style/accessibility#ease-of-reading) - 26
Medusa - [In internal Vale rule](https://github.com/medusajs/medusa/blob/1acfdc4ffe53c3282315d4766359d6c9d601566e/www/vale/styles/docs/SentenceLength.yml) - 30
RedHat - [Style Guide](https://redhat-documentation.github.io/vale-at-red-hat/docs/main/reference-guide/sentencelength/) - 32
Meilisearch - [In internal Vale rule](https://github.com/meilisearch/documentation/blob/b6837449f09587f9d6df92e1eea0c44cc394f398/.vale/styles/Meilisearch/SentenceLength.yml) - 40
Docker - [In internal Vale rule](https://github.com/docker/docs/blob/main/.github/vale/Docker/SentenceLength.yml) - 40

An alternative that I mentioned was to introduce two goals. For example, to suggest keeping sentences to 20 words and making allowance for sentences with technical terms such as RADIUS to 28 words.

Either way, I would argue that 20 words is unenforceable for network related software.

**Comment by alexvonme** [comment]
> I did a research on tech writing resources: Some of them confirm our stance be recommending up to 20 words: [MDN](https://developer.mozilla.org/en-US/blog/technical-writing/) or [Proxmox](https://pve.proxmox.com/wiki/Technical_Writing_Style_Guide#:~:text=Sentence%20length,-Use%20short%20sentences&text=In%20general%2C%20an%20average%20of,%2C%20read%2C%20and%20understand%20information.) Some agree on 25 words, like [here](https://www.enago.com/academy/how-to-optimize-sentence-length-in-academic-writing/). Some allow up to 30 words: [MIT](https://web.mit.edu/juggler/www/ocw/ocw_lectures/class01/lecture_shorten_sentences.htm)

The MIT suggestion may be useful to craft an alternative here. Like them, SUSE could suggest aiming for 20 words while introducing a somewhat hard limit of 28. This could easily be applied through Vale with two separate rules. One that raises a light warning to keep the sentence below 20 words while a second higher suggestion (or even the highest, an error) rule that enforces the 28-word limit. Introducing a goal and a limit separately is relatively uncommon, but hardly unprecedented.

**Comment by cwickert** [comment]
> To illustrate with an example, the [RADIUS section](https://kanidm.github.io/kanidm/stable/integrations/radius.html) of the documentation starts with the following sentence:
> 
> `Remote Authentication Dial In User Service (RADIUS) is a network protocol that is commonly used to authenticate Wi-Fi devices or Virtual Private Networks (VPNs). `

IHMO this a bad example as the written out acronyms already make 11/20 words. You don't have to write out VPN here, this is common knowledge.

But even then you could simplify to 20 words:
`Remote Authentication Dial In User Service (RADIUS) is a network protocol to authenticate Wi-Fi devices or Virtual Private Networks (VPNs). `

Nevertheless I'm fine with 25 words.

**Comment by dariavladykina** [comment]
The Stylewich committee has decided to raise the word limit to 25 words. The style guide will be updated, too.
@alexvonme please feel free to update it in the PR. Thank you!

**Comment by alexvonme** [comment]
Happy to be of service. Thanks for seriously engaging with my arguments. I'll update the Vale style guide shortly.
