### ISSUE TITLE
new definition: command, tool, program, application

### ISSUE THREAD

**Issue by tomschr** [SUSE/doc-styleguide#3]
The above terms pop up frequently and sometimes it's hard to use it right.

See also our [Trello board](https://trello.com/c/CsOWtkyi/29-standardise-one-multiple-of-app-lication-software-program-me)
Here are some definitions from https://www.wordnik.com:
- application
  - A computer program with a user interface.
  - A computer program or the set of software that the end user perceives as a single entity as a tool for a well-defined purpose. (Also called: application program; application software.)
- command:
  - A directive to a computer program acting as an interpreter of some kind, in order to perform a specific task.
  - A signal that initiates an operation defined by an instruction.
- program
  - A software application, or a collection of software applications, designed to perform a specific task.
  - a sequence of instructions that a computer can interpret and execute
- tool:
  -  An application program, often one that creates, manipulates, modifies, or analyzes other programs.
  - A mechanical device intended to make a task easier
  - A piece of software used to develop software or hardware, or to perform low-level operations.
- script
  - A simple program in a utility language or an application's proprietary language.
  - A prewritten list of commands, and perhaps other control information, to be executed (interpreted) by a shell or other command interpreter.

**Comment by dariavladykina** [comment]
Proposal to include the following definitions (from current sources) into the style guide:
 
- program
A set of coded instructions that enables a machine, especially a computer, to perform a desired sequence of operations (www.wordnik.com).

- application
A computer program designed for a specific task or use (www.wordnik.com).

- command
A signal that initiates an operation defined by an instruction (www.wordnik.com).
 
- tool
A piece of software used to develop software or hardware, or to perform low-level operations (www.wordnik.com).
OR: An element of a computer program (such as a graphics application) that activates and controls a particular function (www.merriam-webster.com).

- script
A sequence of instructions or commands for a computer to execute (www.merriam-webster.com).

**Comment by tomschr** [comment]
Thanks Daria for your work. I'm sorry, but I think the last one for script is misleading. 

With the script definition, this could be also used for a program: it also contains also a sequence of instructions. However, what differentiates a program from a script is that a script is executed by a _shell_ or an _interpreter_. That's why we say _shell scripts_, _Python scripts_... but usually not _shell programs_, _Python programs_...

**Comment by dariavladykina** [comment]
Thank you Toms!

Let us use the definition that you suggested for _script_ back in 2015:
A prewritten list of commands, and perhaps other control information, to be executed (interpreted) by a shell or other command interpreter.

**Comment by janajaeger** [comment]
Great list. And thanks for resolving the script issue. List looks good.

**Comment by jfaltenbacher** [comment]
Hi all,
I have checked the Microsoft termbase and found these definitions.

**program**: A set of instructions that a computer or device uses to perform a specific task, such as word processing, accounting, or data management. (similar to the definition we have)

**application**: A set of instructions that a computer or device uses to perform a specific task, such as word processing, accounting, or data management. (I like our definition better)

**command**: An instruction to a computer program that, when issued by the user, causes an action to be carried out. (similar to ours)

**tool**: A utility or feature that aids in accomplishing a task or set of tasks. (short and clear)

**script**: A program that invokes other programs in order to accomplish its tasks. (I like ours better)

Don't want to start a complete new discussion, just as additional info. Usually the Microsoft termbase offers quiet good definitions ;)

**Comment by janajaeger** [comment]
MS's "tool" definition is wayyyyy better than what we have. I would totally like to see this in our style guide. As Julia stated, the rest should stay as suggested by Daria.

**Comment by dariavladykina** [comment]
Since we cannot quite MS glossary directly, how about this for the '**tool**'? 

A utility or feature used to develop software or hardware, or to perform particular tasks.

**Comment by janajaeger** [comment]
I like it!

**Comment by dariavladykina** [comment]
Closing this as the terms have been added.
