### ISSUE TITLE
"based on" v/ "based upon"

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#30]
clarify..?

**Comment by sknorr** [comment]
The case is pretty clear:

189 x based on in XML (0 x based on in entities)
0 x based upon in XML (0 x based upon in entities)
3 x base on in XML (0 x base on in entities)
0 x base upon in XML (0 x base upon in entities)

**Comment by dariavladykina** [comment]
Closing this as not relevant.
