### ISSUE TITLE
hugepage or huge page?

### ISSUE THREAD

**Issue by dariavladykina** [SUSE/doc-styleguide#302]
I believe we should fix the spelling of this term.
In the [THP project](https://docs.kernel.org/admin-guide/mm/transhuge.html), the mentions are inconsistent: both 'hugepages' and 'huge pages'.
In `sle` documentation, we have a prevalence of 'hugepages' 67 vs 31 'huge pages'. But of these 67, most instances are in commands, so the useful majority is with 'huge pages'. 
[Google Trends](https://trends.google.com/trends/explore?cat=5&date=today%205-y&q=hugepages,huge%20pages&hl=en) show a tendency towards 'hugepages'.
However, major resources like IBM, Red Hat, Debian, Kubernetes stick with 'huge pages'.
My suggestion is to fix 'huge pages' in TermWeb and mention the Linux Kernel project's spelling, Transparent HugePage Support.

**Comment by jfaltenbacher** [comment]
looking at the sources, I get the feeling that 'hugepage' is more common than 'huge page'

**Comment by dariavladykina** [comment]
Added to TermWeb as the generic 'huge pages' and the memory feature 'Transparent HugePages'.
