### ISSUE TITLE
"Flash disk" proposal is weird

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#34]
USB mass media does not just come in the shape of flash-based sticks, but also hard disks etc.

**Comment by sknorr** [comment]
Commented this check in SDSC now...

**Comment by taroth21** [comment]
I just talked with Dima, and we agreed that the 'disk' part is weird - how about changing this to 'USB flash drive'?

**Comment by dariavladykina** [comment]
We still have "flash disk" as preferred in DSG. When we decide on the wording, let's also add it to TermWeb.

**Comment by dariavladykina** [comment]
I have found 'USB flash drive' in [Wikipedia](https://en.wikipedia.org/wiki/USB_flash_drive). 
I'd suggest to use 'USB drive', the preference for which is shown e.g. in [Trends](https://trends.google.com/trends/explore?q=USB%20flash%20drive,flash%20disk,USB%20drive&hl=en).

**Comment by cwickert** [comment]
We already have the following in generic-entities:
<!ENTITY usbflashdrive          "USB flash drive">
<!ENTITY usbflashdrivecap       "USB Flash Drive">

However hardly anybody uses this entity. :-( Therefore we also have "flash disk", "flash drive", "flash device", "USB flash disk" etc.

**Comment by dariavladykina** [comment]
Committee has agreed on 'flash drive'.
