### ISSUE TITLE
Packages: "Removal" v/ "Drop" v/ "Deprecation" v/ "Obsolescence"

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#36]
Working on the release notes, I noticed that these terms were applied in a rather haphazard fashion. Would be very good to have firm definitions.

Preliminary ideas on this:
- "deprecated": will be removed in a later version
- "dropped" == "obsolete" == "removed": has been removed in the current version or a prior version. We should use "removed," as it is clear, practical, and non-colloquial. "dropped" is practical, but colloquial and a bit less clear. "Obsolete" is rather theoretical, cloudy, but non-colloquial.

**Comment by dariavladykina** [comment]
Good point, shall we define these in TermWeb?

**Comment by dariavladykina** [comment]
Define 'removal' and 'deprecation', drop the other 2.
