### ISSUE TITLE
Add more terminology that should not provoke any questions...

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#37]
... usually these are just product names, written as the vendor/project does.
- [x] Hyper-V
- [x] PolicyKit
- [x] SR-IOV
- [ ] Fibre Channel & FCoE/Fibre Channel over Ethernet
- [ ] GlusterFS
- [x] XFS
- [ ] AMD-V/AMD Virtualization (not *AMD-VTM, not *AMD-VirtualizationTM)
- [x] Docker
- [x] BlackBerry [ok, there is the question whether we really need that...]
- [x] Android
- [x] iOS
- [x] SUSE SolidDriver Program/SolidDriver

**Comment by dariavladykina** [comment]
Hyper-V is an entity
PolicyKit is deprecated
SR-IOV is consistent
Fibre Channel is not consistent in capitalization
I couldn't find GlusterFS
XFS is consistent
AMD - found one instance of "AMD-Virtualization"
Docker is an entity
BlackBerry is correct
so are Android and iOS
SUSE SolidDriver Program is consistent

**Comment by jfaltenbacher** [comment]
I would avoid adding third party product names to the styleguide, unless some have really suffered from incorrect spelling

**Comment by cwickert** [comment]
Ignore BlackBerry, Android, and iOS, the rest looks save. Glusterfs is a must, should probably be an entity.

AMD-V and AMD-Vi are rarely used, but I think we should add them nevertheless to avoid misspellings/mis-capitalizations.

**Comment by dariavladykina** [comment]
Please check if I got these correctly:

AMD Virtualization (AMD-V) - a set of hardware extensions and on-chip features for the AMD family of x86 microprocessors.
AMD-Vi - a processor feature that enables virtualization of I/O resources (directed I/O).
GlusterFS - a scalable network filesystem suitable for data-intensive tasks such as cloud storage and media streaming.

**Comment by cwickert** [comment]
> AMD-Vi - a processor feature that enables virtualization of I/O resources (directed I/O).

It's AMD-specific, Intel's implementation is called "VT-d" (Virtualization Technology for Directed I/O"). This is kind of mixing both.

How about

> AMD's implementation of a I/O Input–output memory management unit (IOMMU) that enables guest virtual machines to directly use peripheral devices.

or shorter

> AMD's IOMMU implementation that enables guest virtual machines to directly use peripheral devices.

**Comment by dariavladykina** [comment]
Added to TermWeb
