### ISSUE TITLE
New Term: Changelog

### ISSUE THREAD

**Issue by tomschr** [SUSE/doc-styleguide#4]
IMHO, it would be good to add the term "Changelog" to our terminology list.

Currently, I see different spellings: changelog, Changelog, ChangeLog, etc.  It would be good to have one, consistent one.

I found a good definition from https://www.wordnik.com/words/changelog :

> Changelog:
>    A log that records changes between versions, as in source control.

**Comment by sknorr** [comment]
I think just using "change log" is the best option here.

**Comment by dariavladykina** [comment]
The entry will be added as 'changelog'
https://en.wikipedia.org/wiki/Changelog

**Comment by dariavladykina** [comment]
This item is going into the term base after the merge https://github.com/SUSE/doc-styleguide/pull/187, so it is safe to close this issue.
