### ISSUE TITLE
Define how to handle external resources

### ISSUE THREAD

**Issue by tomschr** [SUSE/doc-styleguide#40]
What should be done when we include external resources like images?

Define how we collect the resources and how we refer to the originator/creator.

Suggestion: Add "(Source: Wikipedia, CC-BY 3.0)" into `title` (should we use the `caption` element for this?)

**Comment by sknorr** [comment]
There also is the legal issue of which images are even allowed, e.g. can we use CC-BY-SA? Or not?

**Comment by dariavladykina** [comment]
In Table 5 of the style guide (page 28), the web link for the <imagedata/> element that points to an external image file lands on the 'glossary' term.
