### ISSUE TITLE
activation code v/ registration code

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#42]
Terminology issue ... also for the SCC/YaST teams. In doc-sle, we have:

13 x registration code in XML (0 x registration code in entities)
2 x activation code in XML (0 x activation code in entities)

**Comment by dariavladykina** [comment]
'Activation code' can still be found in doc-sle. Add 'registration code' as preferred to TermWeb?

**Comment by dariavladykina** [comment]
Added to TermWeb, closing.
