### ISSUE TITLE
mounting point v/ mount point

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#45]
Should be mount point, I think... Stats for doc-sle:

86 x mount point in XML (0 x mount point in entities)
3 x mounting point in XML (0 x mounting point in entities)

**Comment by dmpop** [comment]
Mount point is the correct option. Mounting point is a point that mounts something, which makes no sense. :-)

**Comment by dariavladykina** [comment]
Closing, no 'mounting points' in docs
