### ISSUE TITLE
Changing to directories?

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#46]
Reviewer Jack found the following (as-intended) use of the word "change":

```
Create the /web directory and then change to it:

   sudo mkdir /web  &amp;&amp; cd /web
```

Suggestion was to use "change it to" instead. This hints at "change" being used in a jargon-y way here. Reconsider the use of this word? However, the very action performed here, using "cd", is named for "change directory"...

Maybe "switch" is a good option?

**Comment by dmpop** [comment]
*Switch* is the only correct option. You can't change in to directory.

**Comment by dariavladykina** [comment]
The phrase is still there in `doc-sle` but it's the only example. 'Switch to' is used in all other texts, so closing this for now.
