### ISSUE TITLE
AND vs. OR

### ISSUE THREAD

**Issue by cwickert** [SUSE/doc-styleguide#47]
While incorporating proof reading changes into the Virtualization Guide, I came across the following sentence:

> This approach is shared with other technologies, such as Fibre Channel, ATAPI, or USB devices.

The suggested fix was 

> … ATAPI, and USB devices.

This makes me wonder if we use the words _'and'_ and _'or'_ in _common_ or a logical way (all conditions must be met vs. any condition is fine). Most readers would just use 'and' for enumerations, but many of our readers are probably programmers and note the difference.

Some interesting points at:
http://english.stackexchange.com/questions/153222/and-vs-or-when-specifying-a-collection

To make things more confusing, we would need _'and/or'_ in the above example, because the SCSI pass-through can be shared with more then one technology. However, [use of 'and/or' is discouraged](http://data.grammarbook.com/blog/effective-writing/what-about-andor/), one should use _'x or y or both'_ or _'x or y or z or any combination of the aforementioned'_.
Some people [suggest 'aor' or 'XOR' as alternatives](http://english.stackexchange.com/questions/1655/alternatives-to-and-or), but I don't think this is a good idea. :-)

**Comment by dariavladykina** [comment]
We have prepared an article on this topic (inspired by it, actually) for 'Writer's Closet 3' in the upcoming Newsletter. 
TBH, I believe this is rather the question of the English language than the style guide. 
Let's think whether we need detailed explanations in the style guide?

**Comment by cwickert** [comment]
You are probably right. Let's keep it simple.
