### ISSUE TITLE
Insertions of "however"

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#49]
...should be forbidden: They are not very translation-friendly (say I, with zero to show for that claim), and not overly reading-friendly either. Example:  "This process, however, is very time-consuming..."

Not sure where we could put that...

**Comment by dmpop** [comment]
Perhaps discouraged rather than forbidden. There are situations, where *perhaps* works better than *but*.

**Comment by sknorr** [comment]
To be clear, this is only about mid-sentence insertions which is nearly always avoidable, not about the word "however" itself.

**Comment by dmpop** [comment]
I see. Makes sense.
