### ISSUE TITLE
Plural or Singular for Short and Long Options?

### ISSUE THREAD

**Issue by tomschr** [SUSE/doc-styleguide#52]
In one of the SLE RT manuals, there is this sentence:

```xml
[...] use the <option>-l</option> or <option>--log</option> options
with a file name as an argument to [...]
```

What is appropriate for the word "option"?

Should we define long and short options as a singular form? Like their form a single option (=singular) which has two incarnations, a short and a long form?

Or are there two options (=plural)?

Probably the better solution would be to drop one option altogether... ;-))

**Comment by sknorr** [comment]
I think in this case, it is legitimately the same option. But that may not be the case each time, sometimes short options may actually combine a normal long option with an attribute for it (if that makes sense). Not sure we should handle those cases the same or not.

**Comment by sknorr** [comment]
Actually, looking at this again, plural makes sense: Those are two options (that "coincidentally" do the same thing). I am not sure that it makes sense to add this specific case to the style guide. Feel free to reopen if you disagree.
