### ISSUE TITLE
Capitalization of service pack/Service Pack?

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#54]
Should be somewhere in the terminology section.

Some ideas from dpopov:

* only capitalize when used as part of a product name or a specific service pack is meant.
* always capitalize, because that is easy to check & remember.

**Comment by dmpop** [comment]
I vote for the latter: always capitalize to keep it simple and consistent.

**Comment by dariavladykina** [comment]
Very-very inconsistent throughout the SUSE product and marketing communications (with a tendency towards capitalized everywhere) and in our documentation (capitalized with product names, otherwise not). 
TermWeb contains 'service pack' as non-capitalized.

**Comment by janajaeger** [comment]
Are there other service packs apart from ours? If there are, I'd stick with the "use both" approach. If there aren't, maybe go with "capitalized everywhere"?

**Comment by dariavladykina** [comment]
There are service packs out there, Windows for instance. I believe this is a [common term](https://en.wikipedia.org/wiki/Service_pack) and no need to capitalize when not with SLE 12 etc.

**Comment by dariavladykina** [comment]
We have this term in TermWeb now, so closing.
