### ISSUE TITLE
Terminology: use case

### ISSUE THREAD

**Issue by cwickert** [SUSE/doc-styleguide#55]
We should add "use case" to the terminology to avoid misspellings/inconsistency ("usecase", "use-case").

**Comment by sknorr** [comment]
Go ahead -- Proposal sounds good. Maybe add "business case" as well.

https://github.com/SUSE/doc-styleguide/blob/develop/xml/docu_styleguide.terminology.xml

**Comment by cwickert** [comment]
Fixed in 26426a7.
