### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#59]
As discussed on the (internal) mailing list, it would be great to have recommendations on how to recommend something.

In the past, many authors used passive phrasings like "it is recommended". It would be great to pick an one version from these two:
1. **we recommend ...** [Not quite as official sounding]
1. **SUSE recommends ...** [Makes it very official; probably not great if the company name changes (if this happens again)]

Maybe using both but in different situations would also be possible.

This should also be checkable by SDSC.

(Idea: © Carla.)

**Comment by dariavladykina** [comment]
This addition has been filed and PR merged, closing it now.

**Comment by dmpop** [comment]
Apart the _we recommend_ case, are there any conceivable context, where _we_ is acceptable?

**Comment by dmpop** [comment]
Oops, reopened the wrong issue! Closing it.
