### ISSUE TITLE
"key combination" -> "keyboard shortcut"

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#60]
"key(board) shortcut" has the advantage that it encompasses pressing single keys while a combination must always be 2+ keys. For the user, there is not much difference between pressing 1 key or more keys, so using the same word for both makes sense.

**Comment by dmpop** [comment]
There is no such thing as *key shortcut*, ergo *keyboard shortcut* is the only correct option. :-)

**Comment by sknorr** [comment]
@dmpop amended title to reflect your insight.

**Comment by sknorr** [comment]
While at it, we should outlaw "shortcut key" too.

**Comment by dariavladykina** [comment]
I've compared the usage of `key combination` and `keyboard shortcut` [here](https://trends.google.com/trends/explore?q=key%20combination,keyboard%20shortcut) and would like to ask the committee whether we could indeed change this terminology? The 2017 reasoning makes sense to me.

**Comment by jfaltenbacher** [comment]
too me  _keyboard shortcut_ is the superodinate term and can either be just a single key `F2` or a _key combination_ `Ctrl + v`. 
So it is 2 concepts in the end and both are valid depending on the context

**Comment by PadraigDillon1** [comment]
I agree with Julia's comment.

**Comment by dariavladykina** [comment]
So remove _keyboard shortcut_ from deny list in DSG?
