### ISSUE TITLE
Consider some rules from OpenStack writing guidelines

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#61]
originally reported by toms:

> [T]he OpenStack community has some [General writing guidelines](https://docs.openstack.org/contributor-guide/writing-style/general-writing-guidelines.html). 
> 
> Some rules could be interesting for our style checker too: [Write positively](https://docs.openstack.org/contributor-guide/writing-style/general-writing-guidelines.html#write-positively), [Avoid prepositions at the end of sentences](https://docs.openstack.org/contributor-guide/writing-style/general-writing-guidelines.html#avoid-prepositions-at-the-end-of-sentences), [Do no overuse this, that, these, and it](https://docs.openstack.org/contributor-guide/writing-style/general-writing-guidelines.html#do-no-overuse-this-that-these-and-it) and probably more.
> 
> Probably not all are useful or can even be transformed into a specific regex.

**Comment by dariavladykina** [comment]
Hmm, maybe add "Do not overuse 'this', 'that', etc."? Something else?

**Comment by janajaeger** [comment]
Where does common sense end and where does the style checker start? Maybe let's not blow it up too much? Just my $0.02.

**Comment by cwickert** [comment]
I think one example from the 'Avoid prepositions at the end of sentences' could be added to TermWeb:

"pop up" as forbidden noun, use "appear" instead.

The rest is all nice and fair, but I wonder if we blow up the guide too much.

**Comment by dariavladykina** [comment]
Committee has agreed on not blowing up DSG with these particular items.
