### ISSUE TITLE
Open tab is not correct

### ISSUE THREAD

**Issue by dmpop** [SUSE/doc-styleguide#65]
Open tab is no-no. Should be either *switch to section* or *click on tab*

**Comment by sknorr** [comment]
I am a bit confused by this issue -- do you remember what the point of contention was here?

**Comment by dariavladykina** [comment]
To me, opening a tab sounds OK. We also have "click the tab", "enter the tab", "go to the tab", "use the tab" in our docs.

**Comment by janajaeger** [comment]
I agree. "Open a tab" sounds OK to me. "Entering", however, sounds weird to me.

**Comment by jfaltenbacher** [comment]
'open tab' is commonly used. But I do understand Dimas point. A tab usually does not need to be opened, you just click on it or switch tab or alike.

Microsoft styleguide advises 'Go to tab':
https://learn.microsoft.com/en-us/style-guide/procedures-instructions/describing-interactions-with-ui

**Comment by PadraigDillon1** [comment]
To me 'Open a tab' and also 'Go to tab' sound the best.
