### ISSUE TITLE
Clarify screenshotting of browser windows

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#67]
"Only the contents of the tab" can mean either:

1. just Web content
2. including the URL bar etc. (which might introduce additional differences because of browsers/browser versions/installed extensions)

Also, screenshot guidelines should probably not be nested under "structure," but have their own sect1 (?).

**Comment by PadraigDillon1** [comment]
I would agree not to include the URL bar, unless this is required for the screenshot.

**Comment by dariavladykina** [comment]
The current version says: _When documenting Web applications, only reproduce the contents of the tab instead of the entire browser window._ This is enough and no addition is needed, so closing.
