### ISSUE TITLE
Find a good style for replaceable items

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#7]
Ideas to mix and match from:
-   `ALL CAPS`: usually pretty unique, though does not work well on numbers and in some languages there are no caps
-   `all lowercase`: not too distinct from the text, easier to read if longer 
-   `[IN SQUARE BRACKETS]`: should work pretty much in every language, also it is easy to see whether brackets are in italics
-   `<IN ANGLE BRACKETS>`: looks a bit like an XML tag, bit of a hassle to type `&lt;`/`&gt;`, italics not quite as visible
-   `SPACES_REPLACED_WITH_UNDERSCORES`: makes it easier to see that the replaceable has not ended, may clash a little with the underlines that are below monospaced text anyway

Note that most of these things can also be done via a stylesheet... so hassling authors with this may be optional, actually. (One would need to know whether there are edge cases where e.g. you actually need spaces or so within your replaceable or where brackets are misleading or where all-caps content is actually forbidden.)

[A description of that style should also enter our typographic conventions section.]

**Comment by tomschr** [comment]
It's probably hard to find a style which fits for *all* output formats.

Personally, I prefer CAP STYLE. I would avoid square brackets (`[BLA]`) as it could be misinterpreted as "optional". Angle brackets are a bit better.

I'd say, 80-90% of the cases are fulfilled with the following implementation:

* content of replaceable is rendered in upper case
* if the content is in lower case, the stylesheet transforms it automatically into upper case
* any spaces are converted into `_`

Angle brackets (or any other style) can be implemented through stylesheet customization as well. I would suggest to make it customizable through a parameter. :grinning: 

For the rest, well, we should collect these cases and see, if we really have to make exceptions from our rule.

**Comment by tbazant** [comment]
i totally agree with tomsch's idea, and please turn the angle brackets <> on by default :-)

**Comment by keichwa** [comment]
and translators better do not translate what's in <replaceable>...<replaceable>

**Comment by Vogtinator** [comment]
I prefer that <replaceable/> is only a style modification, like a dashed underline, dotted font or similiar. The content should not be modified, for improved readability.

**Comment by dariavladykina** [comment]
We have the instruction in DSG: 
To mark up text that readers need to replace, use the <replaceable/> element. Capitalize placeholder text in all contexts where this is not detrimental to content intelligibility. Do not use spaces within placeholders, instead use underscores.

Is there anything else to do?

**Comment by jfaltenbacher** [comment]
looks sufficient to me (we could also add this to the docbook tags allow list)

**Comment by dariavladykina** [comment]
@jfaltenbacher, [here](https://documentation.suse.com/style/current/single-html/docu_styleguide/#id-1.10.7.5), right?

**Comment by jfaltenbacher** [comment]
`Capitalize placeholder text in all contexts where this is not detrimental to content intelligibility. Do not use spaces within placeholders, instead use underscores. ` could be added to the description column

**Comment by dariavladykina** [comment]
Closing the issue as this has been implemented.
