### ISSUE TITLE
read-write vs. read/write

### ISSUE THREAD

**Issue by taroth21** [SUSE/doc-styleguide#74]
Decide on preferred spelling (maybe there is a better alternative than the two variants listed above).

**Comment by sknorr** [comment]
i think "read/write" makes most sense and we have already defined the very similar "I/O".

**Comment by dariavladykina** [comment]
`doc-sle`:
30 instances of "read-write"
against
18 instances of "read/write"
Despite that, most computing resources prefer "read/write" so I'd stick to this and add to TermWeb.

**Comment by PadraigDillon1** [comment]
I would agree that read/write would be the preferred option. However, In looking at our legacy term database variations of both of the above exist. The version read-write could be there to be used in conjunction with read-only. 
This could be an example here both are accepted and it will depend on the context that would determine which one to use. 
Thoughts?
