### ISSUE TITLE
Deploy PDF on GitHub's Releases Page?

### ISSUE THREAD

**Issue by tomschr** [SUSE/doc-styleguide#78]
# Idea Description

1. Extend your `.travis.yml` file as described in the [Travis help page](https://docs.travis-ci.com/user/deployment/releases).
1. Create a release on GitHub, usually done with a tag.
1. Travis will build a PDF and upload it on your GitHub [releases page](https://github.com/SUSE/doc-styleguide/releases) (currently empty).
1. Profit! User can download the current PDF without building it.

# Requisites
Not entirely sure, if it is possible to build with DAPS on Travis. Maybe we can use a Docker container as Sven did with susedoc.github.io.

# Examples
* [tomschr/dbcookbook](https://github.com/tomschr/dbcookbook/blob/develop/.travis.yml#L30)
* [docbook/xslt20-stylesheets](https://github.com/docbook/xslt20-stylesheets/blob/master/.travis.yml#L5)

**Comment by sknorr** [comment]
There is no Travis here yet. Feel free to bribe @svenseeberg to add Travis here though.

**Comment by sknorr** [comment]
The style guide is now published at doc.suse.com/style. I guess there is no real need to publish to GitHub pages anymore. Travis for validating would still be nice to have though.

**Comment by sknorr** [comment]
Travis is enabled for this repo now.
