### ISSUE TITLE
XML indentation/line wrapping settings

### ISSUE THREAD

**Issue by sknorr** [SUSE/doc-styleguide#8]
So, it seems to be the consensus to use a single space as indentation and to line wrap after 80 characters (or somewhat less) where possible... This should be in the style guide.

@taroth21, @tomschr, @keichwa Opinions?

**Comment by taroth21** [comment]
Single space indentation and a line wrap after 80 characters would be fine with me.

**Comment by sknorr** [comment]
This is done. We can think about more later.
