### ISSUE TITLE
bare metal/bare-metal/baremetal

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#80]
We need a proper spelling & a definition of the term. via @Loquacity in https://github.com/SUSE/doc-susemanager/pull/116

**Comment by Loquacity** [comment]
https://trends.google.com/trends/explore?date=today%205-y&geo=US&q=baremetal,bare%20metal,bare-metal

Generally, we see words like this move from a two-word formulation, to hyphenated, to concatenated (one word). In this case, though, it seems "bare metal" is being stubborn, and staying as two words, no matter what.

Regarding using a different term, I think "bare metal" is well established within the industry, and using anything else could sound peculiar. Happy to argue the point, though.

**Comment by dariavladykina** [comment]
We have received guidance on the spelling from the SUSE Marketing writing team (Jacob):
bare metal - noun
bare-metal - adj. (**bare-metal hardware**)

Suggested definition (from [SUSE](https://www.suse.com/suse-defines/definition/bare-metal/)):

A computer’s hard disk – the medium on which the operating system is installed. 

Other explanations:

A bare metal system is a [computer](https://techterms.com/definition/computer) that does not include any [software](https://techterms.com/definition/software).

[Bare Metal](https://www.lawinsider.com/dictionary/bare-metal) means, in a Cloud Computing Environment, a physical computer server that is dedicated to one Customer.

**Comment by PadraigDillon1** [comment]
In our old MF Term databse we had a definition from https://www.computerhope.com/jargon/b/bare-metal.htm. I'm not sure if this is still valid in all instances.

**Comment by janajaeger** [comment]
The coputerhope definition looks pretty nice, still. Maybe not the spelling for the adjective, but otherwise I'd say it applies.

**Comment by dariavladykina** [comment]
Suggestion:

`Bare metal` (noun) a computer system without a base operating system or installed applications
`bare-metal` (adjective)

**Comment by dariavladykina** [comment]
Merged, can be closed.
