### ISSUE TITLE
Define how to best integrate long lists of necessary packages, supported hardware, etc.

### ISSUE THREAD

**Issue by tomschr** [SUSE/doc-styleguide#82]
In general, in our documentation we try to avoid long lists of supported devices or other hardware. Usually, we try to link to READMEs or to external links.

Not sure where it can be integrated. I guess, a short sentence should be enough.

Found in [Multipath chapter (Storage Guide)](https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-multipath.html#sec-multipath-hardware-autodetect):

```
17.2.1 Storage Arrays That Are Automatically Detected for Multipathing

The multipath-tools package automatically detects the following storage arrays: 
[... long list ...]
```

**Comment by dariavladykina** [comment]
If we want to add this guidance to the Structure section, what should we define as 'long' and 'normal' lists?

**Comment by tomschr** [comment]
That's a valid and good question. I suppose, there is no easy answer. From my gut feelings, I'd say roughly about 6-8 lines/items. That would be okay, in some rare cases we could raise it to 10-15. But the exact number is to be defined. :wink: 

The above example contains 70(!) lines of packages. I think this is way too much.

Maybe we should go a step back and list some reasons why I think we should avoid such overly long lists:

* Overly long lists will be soon outdated
* Hard to maintain
* Occupies a lot of space in our documentation (although it's maybe a minor issue, but for PDF it still can be)
* Probably highly dependent on the product, the product release, or both.

On the other side, we have some benefits:

* Customers doesn't have to go elsewhere
* Searchable

How to deal with such "overly long" lists?

I would ask the following questions:

1. **Can we move such lists to a package?**
  In the mentioned case, there is the `multipath-tools` package. If we want to avoid this long lists, IMHO it's better to open a bug for this package and suggest to add an addition. That can be a fix in a README or a more extensive documentation update. That depends on the nature of the package. In our documentation we could give the reader the pointer where to find it.
  As the customer usually have this package already installed when the section is read, it might be only a small inconvenience.

2. **In case we don't have a package, can we move it to the release notes?**
  Sometimes it's not possible to pinpoint a package. In such a case I'd try to add it to the release notes.

If that all still doesn't work or is not applicable, then and only then we should add this list.

Does that make sense?

**Comment by dariavladykina** [comment]
Since adding very long lists is a rare case, Stylewich has decided to leave it to the writer's common sense and to solve the possible occurrence of such lists on an ad-hoc basis.
