### ISSUE TITLE
Improve Callout section with <xref/>

### ISSUE THREAD

**Issue by tomschr** [SUSE/doc-styleguide#83]
The [callout section](http://docserv.suse.de/documents/Style_Guide/docu_styleguide/single-html/#sec.callout) describes callouts quite nicely.

However, from time to time, an example requires the same callout number on different lines. This can be done by using one `<co/>` and refer to that with one or more `<xref/>`s.

I would suggest to include such an example, something like this:

```xml
<screen language="python">d1 = dict() <co xml:id="co.dict"/>
d2 = {} <xref linkend="co.dict"/>
l1 = list() <co xml:id="co.list"/>
l2 = [] <xref xml:id="co.list"/></screen>

<calloutlist>
  <callout arearefs="co.dict">
    <para>A dictionary.</para>
  </callout>
  <callout arearefs="co.list">
    <para>A list.</para>
  </callout>
</calloutlist>


```

**Comment by dariavladykina** [comment]
Closing this as the addition has been merged.
