### ISSUE TITLE
back-end should be backend

### ISSUE THREAD

**Issue by dmpop** [SUSE/doc-styleguide#85]
There are actually no clear rules governing compound nouns, i.e., both *backend*, *back end*, and *back-end* are correct. See, for example: https://dictionary.cambridge.org/de/grammatik/britisch-grammatik/about-nouns/nouns-compound-nouns

However, *back-end* can be misinterpreted as an adjective, and *back end* can introduce ambiguity in certain contexts. So to simplify things, it would make better sense to write compound nouns as one word.

**Comment by sknorr** [comment]
(Note that "front-end"/"frontend"/"front end" should be adjusted analogously.)

**Comment by dmpop** [comment]
Yes, analogously.

**Comment by Loquacity** [comment]
IBM recommends the hyphenated version.

**Comment by dmpop** [comment]
Yeah, but that's IBM. The New York times punctuates most of there abbreviations (e.g., G.D.P.R.), which is on the same level of silliness. :-)

**Comment by sknorr** [comment]
Whatever level of silliness one assigns to this spelling (which is essentially an arbitrary/personal value), the fact that we've been writing like that for multiple years should be taken into consideration.

I know some of our docs are not style checked particularly well, but e.g. SLES docs are. So, there's an obvious disincentive to change the spelling of this rather common term if both versions are correct (as in: work for writers, cost for retranslation).

**Comment by dmpop** [comment]
@Loquacity Ah, that makes perfect sense. :-)

@sknorr Good point. Feel free to ignore/close this bug.

**Comment by sknorr** [comment]
At @dmpop's behest ... Closing this until he comes up with either:

* better arguments
* meaner taunts for me
