### ISSUE TITLE
Which tag to use for subcommands?

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#86]
What tag should be used when describing e.g. the `pull` in `git pull`? (For clarification, this is within running text, not within \<screen\>.)

@fsundermeyer suggests the following three options:

* `<command>` [it sort of acts like a command] (@tomschr is in favor)
* `<option>` [it's placed like an option, i.e. after the actual command's name] (@svenseeberg is in favor but he's going to leave the company soon)
* `<literal>` [it is neither of the above and we don't really have anything specific for that case] (@sknorr is in favor)

**Comment by sknorr** [comment]
@Loquacity, that is a valid way of looking at it as well and it neatly sidesteps the issue for the most part.

@fsundermeyer Would Lana's suggestion cover the specific case you had?

**Comment by sknorr** [comment]
Ok, just to note the context here (before I forget): Frank had created a variablelist of subcommands, in a style like this:

```
The following subcommands are available for `git`:

pull
     Pulls stuff

push
     Pushes stuff

status
     Shows the status

...
```

& he was wondering how to format the `<term>`s in it.

**Comment by fsundermeyer** [comment]
Lana's solution looks like the best option for me in floating text. As a consequence I would also use <command> in the variablelist.
