### ISSUE TITLE
Link to PDF of stable version is broken

### ISSUE THREAD

**Issue by taroth21** [SUSE/doc-styleguide#9]
The style guide GH page states: 
'A PDF can be reached in different versions:
* the stable version
* the development version'

Whereas accessing the development version works, the link to the stable version seems to be broken (gives me a 404 error): https://github.com/SUSE/doc-styleguide/raw/master/prebuilt/current/styleguide_with_changelog.pdf

**Comment by sknorr** [comment]
Closing this -- toms seems to have accidentally broken this when he renamed the styleguide PDFs (but only on develop, not on master). But it has been working again for a while now.
