### ISSUE TITLE
Use/omit the article when using xref or citetitle to reference other guides?

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#91]
When referencing another guide with either citetile or xref (because that should be consistent), should we do it like:

* **No article:** For more information, see *Administration Guide*.
  * flows less naturally
  * makes it easier to change reference to something else later on (without having to think about whether articles are useful there)

* For more information, see the *Administration Guide*.
  * flow more naturally in many cases
  * means you have to think about how you change references if you need to do so later on
  * if the referenced `id` wanders onto another element, there might be an automatic change that you don't notice but will lead to a completely unnatural sentence.

**Comment by dariavladykina** [comment]
I looked at a few books in `doc-sle`, `doc-sleha` and `doc-slesforsap` and somewhere this is not consistent.
I'd suggest adding the instruction to the Structure and Markup chapter in this [subsection](https://susedoc.github.io/doc-styleguide/main/html/style-guide/index.html#sec-structure#sec-link) like this:

Do not use <link/> to link to SUSE documentation outside of the current document set. Instead,
use the appropriate entity for the book title. Always reference the book itself, as chapter names
can change.
For consistency, do not use the article in front of the name of the referenced book. For example, "For more information, see Administration Guide."

**Comment by dariavladykina** [comment]
Closing this as the improvement has been merged.
