### ISSUE TITLE
Try to find a different program to recommend rather than Shutter

### ISSUE THREAD

**Issue by sknorr** [SUSE/doc-styleguide#96]
Shutter has (had?) issues working on PCs with NFS-mounted homes (though that is gradually becoming less relevant). https://bugs.launchpad.net/shutter/+bug/1003185

[originally reported Feb 24, 2014 in Trello.]

**Comment by lproven** [comment]
@cwickert recommended Nimbus to me:
http://nimbus-screenshot.everhelper.me/releasecapture-ff.php
