### ISSUE TITLE
add kernel to terminology?

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#97]
It used to be a rule that *kernel* be capitalized where it referred to the Linux kernel. However, that rule produced many style checker messages for compounds like *kernel patch*.

Since the rule was removed in 2014-02.1, the term *kernel* is currently not controlled.

[originally reported May 7, 2014 in Trello.]

**Comment by dariavladykina** [comment]
There is "Linux kernel" in TermWeb, is it enough?

**Comment by PadraigDillon1** [comment]
I think it's enough.

**Comment by cwickert** [comment]
Kernel should not be uppercase, nothing to check.
