### ISSUE TITLE
Company-wide Terminology Database

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#98]
This is something for the future...

Discuss if we could establish a "company wide" terminology database. It seems to me, this would be beneficial to other departments as well as translators. A consistent use of SUSE terms would be helpful.

Things to remember/discuss:

* Who maintains this terminology [database]?
* How can new terms be suggested/added?
* Define scope: only English, or other languages?
 

Things that could help:

* Tekom booklet about Terminology
* inter-departmental collaboration
* The openSUSE community?

**Comment by dariavladykina** [comment]
Closing this as we now have one!
