### ISSUE TITLE
passphrase/keyword/password/passcode

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#99]
+ Is a passphrase the same as a password?
+ Only allow **password**?

=> maybe use application standard, do not standardize at a general level

[originally reported Jun 18, 2014 in Trello.]

**Comment by dariavladykina** [comment]
We have 82 instances of 'passphrase' in doc-sle, but it's hard to tell whether they are the same as 'password'.

**Comment by jfaltenbacher** [comment]
I opt for 'use application standard, do not standardize at a general level'

**Comment by dariavladykina** [comment]
Closing this as nothing to do.
